### ISSUE TITLE
ConicBy4p1l doesn't trace

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#101]
`geoOps._helper.ConicBy3p2l` doesn't do any tracing, so its outputs may get swapped arbitrarily.

**Comment by strobelm** [comment]
This shouldn't be very difficult to do, i'll add the code.

**Comment by gagern** [comment]
As far as I can tell, ConicBy3p2l should do tracing since 614e6047a28911a14735865fa586f81cacf8b52c, perhaps even since 1cf2527a493bb9c15cbe3a7052d430337e4ee263. So I *guess* that this bug report here was not about that but about `geoOps._helper.ConicBy4p1l` instead, which does *not* do tracing today. @strobelm will you take care of this, or should I add tracing to that? Since I intend to base the multi-valued parts of #320 on that, the scope of this bug here will likely increase to more operations.
