### ISSUE TITLE
Support Text in geometry

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#14]
We should support Text as a geometric element. In its easiest form, the renderer could translate this directly to a call to drawtext. For added compatibility, we should also support styling text as buttons, with all the machinery associated with this. And there is also `EditableText` to provide a text input field.

* [x] plain text printed
* [x] value substitution for measurements
* [x] docking to points
* [x] docking to window edges and corners
* [x] newlines in static text
* [x] button styling, both pressed and non-pressed
* [x] push button triggers script
* [x] toggle button has accessible state
* [x] editable text shows text field
* [x] text of editable text field accessible from CindyScript
* [x] editable text actually is editable
* [x] reasonable input focus handling

**Comment by kortenkamp** [comment]
This feature is a showstopper for most of the interesting examples. It is urgently necessary to implement this, so I comment here to push it on top of the to-do list…

**Comment by kortenkamp** [comment]
Just a meta-question – who is able to edit and assign issues?

**Comment by kranich** [comment]
>Just a meta-question – who is able to edit and assign issues?

People with Write, Admin, or Owner permissions, see

https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by kortenkamp** [comment]
ok… thanks to Martin I am now able to assign people to this task - thank you! 

@gagern - if you don't like this assignment, please find somebody else… I  really think this is urgent.

**Comment by gagern** [comment]
@kortenkamp Since I already did work on the first few points here for #225, it's only natural that I'm the one to continue that work.

**Comment by gagern** [comment]
Finally done.
