### ISSUE TITLE
Inconsistent branch cuts of sqrt

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#15]
*(Manually migrated from GitLab issue 1 reported by @kranich)*

The branch cuts of CindyScript `sqrt` operator differ between Cinderella and cindyjs.

If we plot the square root of a point and move the point around the origin, the square root must jump at some stage.

In Cinderella, this happens when the point crosses the positive real axis. In cindyjs this happens when the point crosses the negative real axis.

This inconsistency can be a real problem when one tries to script certain tracing algorithms.

**Comment by gagern** [comment]
If I remember correctly, @richter-gebert recently decided to stick to Cinderella's semantics.

**Comment by gagern** [comment]
I'd say we use issue asignees to indicate who's going to fix it, and pull request asignees for who's going to review it. In this sense, this ticket is now all yours, @kranich, and I'll have a look at #189 soon.

**Comment by kranich** [comment]
@gagern OK, thank you.

**Comment by kranich** [comment]
Superseded by [Cinderella GitLab issue #132](https://gitlab.cinderella.de:8082/cinderella/driftin/issues/132).
