### ISSUE TITLE
Additional arrow heads

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#152]
Cinderella supports two more arrow shapes which CindyJS does not support at the moment. One is a hollow arrow, like `full` but only stroked not filled. The other is a delta-shaped head somewhere between `default` and `full`, and similar in appearance to arrow heads commonly used in TeX.

I propose the names `hollow` and `delta` for these new types. An implementation would have to extend [`draw_arrowhead`](https://github.com/CindyJS/CindyJS/blob/d39fb3b6d637581ef771e84ec27c8948c24cb4d0/src/js/libcs/Render2D.js#L397-L418), but also find the appropriate [base](https://github.com/CindyJS/CindyJS/blob/d39fb3b6d637581ef771e84ec27c8948c24cb4d0/src/js/libcs/Render2D.js#L365) [positions](https://github.com/CindyJS/CindyJS/blob/d39fb3b6d637581ef771e84ec27c8948c24cb4d0/src/js/libcs/Render2D.js#L374) for ending the line short of the arrow head.

**Comment by gagern** [comment]
I found the Cinderella arrowhead descriptions. The `delta` head, at size 0.2 (according to CindyJS `arrowsize` modifier) with tip at the origin has coordinates `(-3,1), (0,0), (-3,-1), (-2,0)`. For comparison, the `default`, `filled` and `hollow` arrowheads have coordinates `(-2,1), (0,0), (-2,-1)` so they don't form an equilateral triangle (as those in CindyJS do) but instead one with approximately 53° at the tip and 63° at the base. Not sure whether we should switch to these dimensions as well, for the sake of compatibility or aesthetics. Opinions, @richter-gebert or @kortenkamp?

**Comment by elkins0** [comment]
If you look at the "Extra Appearance" tab of the "Information" (Ctrl-I) on a segment and move the pointer over the arrow choices shown, left to right, the tool-tips show `Line`, `Empty`, `Full` and `Jet`. So what you are referring to `hollow` is `Empty` and `delta` is `Jet`. My own spin here is that overall an image would be a better choice especially since these are small decorations which are of fixed rather than geometry dependent sizes.

**Comment by gagern** [comment]
@elkins0 Thanks for suggesting tool tips for naming, I hadn't thought of that. My pull request for Cinderella has already been merged, though, so I can't just change that but would need a second modification to change the names to match the tooltips. @kortenkamp, do you think we should do so?

I think we definitely don't want to use a raster image to draw the arrow head, for several reasons. Most importantly, the arrow head has to match its line in color, opacity and line width, and its size is flexible as well. Rendering arrowheads using vector graphics is far easier and yields better results. The outline is easy enough.

**Comment by elkins0** [comment]
By the way, have you ever considered extending arrowheads to arcs? When reflected in a circle mirror segments turn into arcs and loose any arrowheads they may have had.

**Comment by gagern** [comment]
@elkins0 I have considered it. Judging from a quick glance at the Cinderella code, there seems to be some support there for specifying arrowheads for arcs, but none to render them.

Getting arrowheads for arcs right is tricky business, though: simply having the arrowhead take its tip position and direction from the end of the arc will cause the line of the arc to pass through the base off-center and non-orthogonally, which looks somewhat weird in my opinion. So one would have to bend the arrowhead itself, I think. I believe I've seen this done somewhere. Maybe Asymptote. Certainly worth some experimenting.

**Comment by kortenkamp** [comment]
@gagern I think we should change the names to match the tool tips, I don't mind another merge request.
