### ISSUE TITLE
some make errors hard to understand

### ISSUE THREAD

**Issue by montaga** [CindyJS/CindyJS#153]
Hi folks!
I just compiled the CindyJS on a new machine and spent some time notice that java is required for closure.
The error that was displayed was the following:

java ... [a bunch of several lines]
execvp(): No such file or directory
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
From previous event:
    at Array.reduce (native)
    at Task.run (/home/aaron/m10/CindyJS/make/Task.js:225:22)
From previous event:
    at /home/aaron/m10/CindyJS/make/Task.js:193:18
Makefile:2: recipe for target 'all' failed

(I had problems reading from that that java is missing)
It would be cool if there was an automatic test that detects whether there is a working version of java, npm, node

**Comment by gagern** [comment]
Good point, will see to it.

**Comment by gagern** [comment]
On my system, node does include the name of the command in the error message. Nevertheless, the stack trace is still confusing, and we don't want to force people to use my version of node either. The fix https://github.com/gagern/CindyJS/commit/56b8b45f370d07c287a17a9055329daa5528355d is included in #154 and waiting for review.

**Comment by gagern** [comment]
Closed via #154.
