### ISSUE TITLE
mover() inconsistency

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#16]
_(Manually migrated from GitLab issue 3 reported by @kranich)_

In Cinderella, `mover()` yields the element which has last been moved. In cindyjs, `mover()` yields the element which is currently being moved.

Hence, mover produces different behaviour on mouse up (`_?_` in cindyjs vs. the element which has last been moved in Cinderella).

---

_(Comment originally by @kortenkamp)_

The Cinderella behavior is the preferred one, IMHO. Of course, one could create a workaround and store the current moving element, but this creates ugly code.

Also needs a comment from @richter-gebert

**Comment by gagern** [comment]
It was decided that the CindyJS behavior should stay, and that Cinderella should use the CindyJS semantics when executing the code as CindyScript 3. The main benefit is that this allows scripts to easily detect whether some element is being moved or not. The woraround to store the mover in a variable is easy enough that essentially no functionality is lost, even if some code may need some adjustments.

**Comment by kranich** [comment]
Superseded by [Cinderella Gitlab issue 162](https://gitlab.cinderella.de:8082/cinderella/driftin/issues/162).

**Comment by kortenkamp** [comment]
I would like to discuss this issue again with regard to multi-touch (not meaning that I think it should not be closed finally): What should mover() return if several elements are moved quasi-simultaneously? Say, we get a touchdown on A, touchdown of B, touchdown C, touchup A, touchup C, touchup B.  

I will write the (maybe) expected mover() variable next to each item:

TD A – A
TD B – B
TD C - C
TU A - C
TU C - B
TU B - null

Now, with the current Cinderella behavior you will get

TD A - A
TD B - B
TD C - C
TU A - C
TU C - C
TU B - C

So, concluding: If you want `mover()` to become `null` then you have to maintain a stack of movers().

I remember the old days when it was not granted that you received a mouse up for every mouse down. Does anybody know whether this is guaranteed for JavaScript?

So, I invite everybody to rethink this, even if it just leads to the same final conclusion.

**Comment by kortenkamp** [comment]
And let me add something else: It is **essential** to receive the last mover() in the mouse up event! Just consider the following code:

In mouse down:
```
mover().size=20
```

In mouse up:
```
mover().size=5
```

This is not uncommon. So... I am strongly opposed to setting `mover()` to `null` already in mouse up. It might be ok **after** mouse up.

**Comment by gagern** [comment]
Yes, `mover()` should only become nada *after* the mouseup code got executed.

In mouse-related event scripts, `mover()` should imo always return the element related to the current stream of touch events. In the draw script and similar, chances are that we’ll violate some reasonable assumptions no matter what we do. So perhaps we really should provide `movers()` and even print a warning to console indicating that it should be preferred over `mover()` outside touch events.

That leaves `mover()` outside mouse events essentially as a compatibility feature. And as such, I’d say it should try to follow Cinderella semantics. But since Cinderella semantics are changing with CindyScript 3, we still can think about what would be best. What you suggest makes sense: of all the active movers return the one that started moving most recently.

**Comment by kortenkamp** [comment]
Pinging this issue, as I ran into trouble with `mover()` again with the Stellenwerttafel example, see #895 that adds the example file.
