### ISSUE TITLE
Problem with triangles and lines

### ISSUE THREAD

**Issue by bellezaodiada** [CindyJS/CindyJS#166]
The following code to demonstrate Desargue's theorem does not work in CindyJS but perfect in the java version. The triangles no longer fill with colour and some lines are cut short.
The original Cinderella file is attached and so is the "exported to CindyJS" file. All using version 2.8 build 1781

[desargues.zip](https://github.com/CindyJS/CindyJS/files/93420/desargues.zip)

**Comment by strobelm** [comment]
Hi! The problem is caused by Poly which is not implemented as geoOps operator. I'll have a look.

**Comment by bellezaodiada** [comment]
Many thanks.

Graham

**Comment by bellezaodiada** [comment]
Michael

Was there any progress on this problem?
My examples of Desargues Theorem still don't work on Cindy JS. Is there 
any likelihood of this being fixed in the reasonably near future.

I attach the Cinderella file as a reminder of the problem.

Many thanks

Graham

**Comment by bellezaodiada** [comment]
Here is the Cinderella file for the Desargues demonstration. Works perfectly in Cinderella with Java but doesn't work in CindyJS
[desargues3d.zip](https://github.com/CindyJS/CindyJS/files/190878/desargues3d.zip)

**Comment by bellezaodiada** [comment]
Closed in error :-)

**Comment by strobelm** [comment]
Hi Graham,

i haven't forgot about the issue and already started writing some code:

https://github.com/CindyJS/CindyJS/pull/173/files

It's not finished yet, i hope i can implement it within the next one or
two weeks.

best regards

Michael

On 03/27/2016 01:25 PM, bellezaodiada wrote:
> Michael
>
> Was there any progress on this problem?
> My examples of Desargues Theorem still don't work on Cindy JS. Is there 
> any likelihood of this being fixed in the reasonably near future.
>
> I attach the Cinderella file as a reminder of the problem.
>
> Many thanks
>
> Graham
>
>
> El 19/01/2016 a las 10:41, Michael Strobel escribió:
>> Hi! The problem is caused by Poly which is not implemented as geoOps 
>> operator. I'll have a look.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/CindyJS/CindyJS/issues/166#issuecomment-172793568>.
>>
>> No se encontraron virus en este mensaje.
>> Comprobado por AVG - www.avg.com <http://www.avg.com>
>> Versión: 2016.0.7497 / Base de datos de virus: 4542/11819 - Fecha de 
>> publicación: 03/15/16
>>
>
>
> ---
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/CindyJS/CindyJS/issues/166#issuecomment-202042041


-- 
Michael Strobel, M.Sc.

Technische Universität München -- Zentrum Mathematik
Lehrstuhl für Geometrie und Visualisierung (M10)
Boltzmannstr. 3, 85747 Garching bei München 
https://www-m10.ma.tum.de/bin/view/Lehrstuhl/MichaelStrobel

**Comment by bellezaodiada** [comment]
Great!
Many thanks

Graham

**Comment by strobelm** [comment]
Hi, sorry that it took so long. A fix is contained in the current master branch.
