### ISSUE TITLE
Segment to far point causes division by zero

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#168]
Consider the segment between two finite points A and B. If we set `B.homog` to coordinates of a far point, drawing the segment leads to a division by zero.

**Comment by gagern** [comment]
Doesn't any attempt to draw a point at infinity lead to a rather harmless division by zero? How is this one special?

**Comment by kranich** [comment]
In an example that I was shown today, we observed an endless stream of "Division by zero" warnings, even when we commented out every obvious division from the code. The error messages somehow seemed to block the entire widget. There was something seriously wrong. I will ask whether I may post the entire example later this week.

**Comment by kranich** [comment]
In any case, we should not fill the console with "DIVISION BY ZERO" errors that are not caused by the user's script.

If there is a segment in a geometric construction and one of its end points becomes a far point, then it is *our* responsibility not to divide by zero. We should handle this special case and not try to draw such a segment.

Cinderella does not spit out any error messages in this case.

**Comment by gagern** [comment]
I agree, we should not print a warning for division by zero inside CSNumber. If we feel a need to inform users of possible problems, we might do so in the implementation of the infix division operator.
