### ISSUE TITLE
Cross-origin resource sharing of KaTeX fonts

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#174]
Apparently, when using KaTeX, fonts cannot be loaded from `http://cindyjs.org/dist/snapshot/katex/fonts/` due to cross-origin resource sharing policies. I see this issue in Firefox but expect this to apply to other browsers as well.

The problem is that no `Access-Control-Allow-Origin: *` header is configured for `cindyjs.org`.

**Comment by gagern** [comment]
I added the header. @kranich, please verify this works now, both for `snapshot` and for `latest`.

**Comment by kranich** [comment]
@gagern It works for both `snapshot` and `latest`.
