### ISSUE TITLE
CSNumber.pow does not work for base 0

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#175]
CindyJS yields `NaN - i*NaN` instead of `0` for `0^(1/4)`.

Cinderella yields `1` for `0^0`. Although I am not sure `0^0` is mathematically well-defined, CindyJS should yield `1` for compatibility with Cinderella.

I will prepare a pull request to fix this.

**Comment by gagern** [comment]
> Although I am not sure `0^0` is mathematically well-defined, […]

See also https://en.wikipedia.org/wiki/Exponentiation#Zero_to_the_power_of_zero

**Comment by kranich** [comment]
@gagern OK, I had the complex analysis definition via log and exp in mind, therefore my doubt. Then CindyJS should definitely return `1` as required by the test case I added.
