### ISSUE TITLE
csplay() is broken

### ISSUE THREAD

**Issue by strobelm** [CindyJS/CindyJS#18]
In the current master the examples (like examples/40_Swarm.html) which use csplay are broken. I bisected the commits and found the faulty commit to be 6a94d0714b62f2783d53b08fcd4cf312a1f81a41.

**Comment by strobelm** [comment]
Thanks a lot @gagern for the fast fix (sorry messed up the commit message, is it worth to fix that?)

**Comment by gagern** [comment]
Don't think so. Particulrarly since updating the history of a public branch (aka forced push) is evil.
