### ISSUE TITLE
CSNumber singletons for Infinity and NaN

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#187]
Do we want CSNumber singletons for Infinity and NaN, much like `CSNumber.zero` and `CSNumber.one`?

I suggest adding

```JavaScript
CSNumber.infinity = CSNumber.complex(Infinity, Infinity);
CSNumber.nan = CSNumber.complex(NaN, NaN);
```

I feel using these would make some code clearer. Opinions?

**Comment by gagern** [comment]
I think it would be a good idea. The only concern I have is that it could tempt programmers into doing checks like `x === CSNumber.infinity` which would work for output coming from the singletons, but not in general. I'm not sure whether this concern is big enough to warrant writing patterns for the `forbidden` step of the build.
