### ISSUE TITLE
drawtable

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#193]
We should implement [the `drawtable` operator](http://cindyjs.org/ref/Texts_and_Tables.html#drawtable$2) in a way compatible to Cinderella.

**Comment by kortenkamp** [comment]
I guess that drawtable can be implemented in CindyScript itself.

**Comment by gagern** [comment]
Does the Cinderella version do any string width measurements to automatically choose column widths? If so, I don't think we have that available in CindyJS. Otherwise I agree, it should be possible.

**Comment by kortenkamp** [comment]
Indeed, this is missing (also in Cinderella). We need it anyway, so maybe it is a good idea to create a new function that can query the size of a rendered string.

**Comment by gagern** [comment]
Another thing we would need before we could define this in CindyScript is to have modifiers in user-written CindyScript functions. I see no reason why we couldn't use a syntax like

    foo(baz, mod1->def1, mod2->def2) := impl

to define a function with some modifiers, providing default values for these. CindyScript currently ignores modifiers on function definition and function call. Cinderella apparently ignores them on function definition, and does introduce temporary bindings for modifiers provided at function call. There is no way to now whether a given symbol came from a modifier or from the global environment, though, making that convention unsuitable as well.

For the time being, a JavaScript implementation (which internally may call the same drawing functions used by CindyScript as well) will probably be easier to implement.

**Comment by kortenkamp** [comment]
I love this idea for providing modifiers in function definitions. There are also other mechanisms, please tell us @richter-gebert - I always forget how to do it.

**Comment by gagern** [comment]
I just opened #205 for Cinderella-style modifier passing at call-time, and #206 for modifiers with defaults inside the function definition.
