### ISSUE TITLE
Quoting parameters in the reference documentation

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#211]
Starting at https://github.com/CindyJS/CindyJS/pull/209#issuecomment-179787875, @strobelm and @kranich have been complaining about the tediousness of using `‹` and `›` (instead of `<` and `>`) when writing reference documentation. I'll quote the discussion there for the sake of completeness.

@strobelm wrote:
> It's a bit tedious to write documentation if the character delimiting the arguments is not on a standard keyboard. Isn't there a better solution than copying the arguments every time?

@gagern wrote:
> @strobelm Your're on Linux, right? In that case I suggest you configure e.g. one of the Windows keys as [compose key](https://en.wikipedia.org/wiki/Compose_key) and edit your [`~/.XCompose` file](http://linux.die.net/man/3/xcompose) to provide you with suitable key bindings. Or go with the default; for a standard libX setup, [`/usr/share/X11/locale/en_US.UTF-8/Compose`](https://github.com/mirror/libX11/blob/7eb724dc24505f1591ef32620fa63f079b540646/nls/en_US.UTF-8/Compose.pre#L109-L110) should contain these settings:
>
>     <Multi_key> <period> <greater>   	: "›"   U203a # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
>     <Multi_key> <period> <less>      	: "‹"   U2039 # SINGLE LEFT-POINTING ANGLE QUOTATION MARK

@kranich wrote:
> I generally agree with @strobel that these symbols are a pain. I would appreciate if we could come with a different alternative. Why can't we just use '<' and '>'? Embedded in backticks there should be no confusion with HTML tags for Markdown.

I have strong objections to using `<` and `>` in the output, i.e. the rendered HTML as it can be seen on http://cindyjs.org/ref/. I don't perceive `<` and `>` as the quotation marks, but as input syntax, so using `‹` and `›` makes the headlines much more readable in my opinion.

I'm less certain on the input side. After all, we are doing [custom formatting for headlines](https://github.com/CindyJS/CindyJS/blob/6963e82ed893cbecae8caa2f3643ac34a4da3df4/ref/js/md2html.js#L66-L117) in any case, so we might as well add a rewrite of `<` and `>` to `‹` and `›` there. The [rendering on GitHub](https://github.com/CindyJS/CindyJS/tree/master/ref) would not benefit from this, but that's acceptable. Hmmm… We should consistently be using this notation not only in headlines, but in the body of the description as well. Consistently distinguishing parameters from e.g. quoted HTML tags (like `` `<script>` ``) there is much harder.

The [`docscrub` tool](https://github.com/CindyJS/CindyJS/blob/6963e82ed893cbecae8caa2f3643ac34a4da3df4/ref/docscrub.py#L57-L60) simply replaces `<` and `>` by `‹` and `›` inside code. On the one hand, this incorrectly converted comparison operators, while on the other hand it missed occurrences of parameters outside code formatting. Both of these have required manual editing in the past.

If you can think of a way to automatically detect all parameters without false negatives or false positives, then I'm willing to investigate this. Until then, I think actually typing the character you want to see in the final output is the most viable solution. You can of course enter HTML character entities like `&#x2039;`, but that's hardly better than copy&paste in my opinion.

You can also think of your own *unique* replacement sequences, e.g. `<!<` and `>!>` or whatever you like, and set up a preprocessing step which converts Unicode input to this and a postprocessing step which converts this back to Unicode input. We could provide standardized git hooks to run these conversions on checkout and commit, I think.

What do you think?

**Comment by strobelm** [comment]
As a workaround i'm using sed -i 's/</‹/g;s/>/›/g' ref/myref.md (for sure there is something better with grouping) and check the result by hand.

**Comment by kranich** [comment]
I have just found out how I can enter ‹ and › on my keyboard without breaking my hands. Let's move on to more important stuff, I'd say.

**Comment by gagern** [comment]
I don't see how the compose key approach would break anyone's hand. Keep in mind that the keys are to be typed *sequentially*, so this is <kbd>Compose</kbd>,<kbd>.</kbd>,<kbd>&gt;</kbd> typed one after the other. I can understand this taking too long for someone's taste, and I can understand this being hard to remember (in which case you might want to reconfigure it to something simpler to remember).

@kranich, could your solution apply to others as well? If so, perhaps you can share it here, so that we can refer other potential contributors to it if the need arises.

In that spirit, the German Mac keyboard has `‹` at <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>B</kbd> and `›` at <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>N</kbd>. The US American Mac layout has `‹` at <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>3</kbd> and `›` at <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>4</kbd>. That's keys to be pressed simulatenously, so it might cause broken hands (for those who haven't already broken their hands typing TeX code on a German Mac layout with `\` at <kbd>⌥</kbd>+<kbd>⇧</kbd>+<kbd>7</kbd>).

**Comment by kranich** [comment]
@gagern On my Colemak keyboard `‹` at <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>[</kbd> and `›` at <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>]</kbd>. On my German keyboard `‹` at <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>X</kbd> and `›` at <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>Y</kbd>.
