### ISSUE TITLE
Complex arctan2 implementation

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#226]
The [current  `arctan2` implementation](https://github.com/CindyJS/CindyJS/blob/1e4083d09e6fbba3a22dde5ca9f2f2cd8bea941d/src/js/libcs/CSNumber.js#L343-L349) is only valid for real-valued input. We should replace that by a version which handles complex input correctly.

**Comment by kranich** [comment]
@gagern What do you mean by 'correctly'? I thought `arctan2` was commonly only defined for real input. I don't think we can translate the concept of quadrants into complex space so easily.

A definition one could think of is 'angle in the range from -pi/2 to pi/2 between positive real axis and point (x,y) in C^2'. At least this would reduce to the usual `arctan2` for real-valued input.

What do you think?

**Comment by kranich** [comment]
Another definition that generalizes straightforwardly would be 'the principal argument of the complex number x + i y'. There it does not matter whether x and y are real or complex. But this is different, semantically.

**Comment by kranich** [comment]
So what kind of definition do we want?

**Comment by kortenkamp** [comment]
Apparently, Wolfram alpha is able to apply atan2 to complex arguments:
http://www.wolframalpha.com/input/?i=atan2(i,-i)

I did not check how they define that, as I also see that "quadrant" is a strange concept for pairs of complex numbers. However, maybe it is sufficient to use atan2(x,y) = - atan2(x,-y) and other properties to find the correct continuation into complex space.

**Comment by gagern** [comment]
I must confess I'm not sure myself. Personally I imagine the real-valued `arctan2` as defined by

    cos(arctan2(x, y)) * |[x, y]| = x
    sin(arctan2(x, y)) * |[x, y]| = y

But I don't even know whether it is possible to preserve this over the complex numbers. Note that the above doesn't make any statement about which branch to choose. I haven't checked how this agrees with either of your definitions.

In your first suggested definition with the angle in ℂ², how would you compute that without already referring to something equivalent to arctan2. If you use Laguerre's formula to define angles, that formula only gives you the angle up to a multiple of π.

The approach with the principal argument of that single number feels very elegant, and should be meromorphic as well. Nevertheless I doubt (based on a gut feeling) that it will satisfy my conditions above. Worth checking, though.

Another definition would be as a function which is equivalent to `arctan(y/x)` mod π, but which is without discontinuities when considering ℂ²\\{(0,0)} as input and  ℂℙ¹ as output. To see whether this definition makes any sense, we'd have to see whether taking different paths in the input space can lead to different branches of the `arctan` function.

**Comment by gagern** [comment]
Looking at [the Wolfram reference for `ArcTan`](http://reference.wolfram.com/language/ref/ArcTan.html), one can read that they defined it like this:

> If *x* or *y* is complex, then `ArcTan[x,y]` gives −*i* log((*x*+*iy*)/√(*x*<sup>2</sup>+*y*<sup>2</sup>)). When *x*<sup>2</sup>+*y*<sup>2</sup>=1, `ArcTan[x,y]` gives the number *ϕ* such that *x*=cos(*ϕ*) and *y*=sin(*ϕ*).

Not sure whether the fact that Wolfram uses it is reason enough to follow the same definition, but lacking a good argument to do otherwise, I'm inclined to use that.

**Comment by kortenkamp** [comment]
This definition makes sense. Basically, `arctan(x)` is the inverse of `x=tan(ϕ)=sin(ϕ)/cos(ϕ)`, and `arctan2(x,y)` is the same inverse but with sin and cos separated. So yes, please use that definition.

You are welcome to adapt that in classic Cindy as well...

**Comment by kranich** [comment]
And for unimodular z, -i log z = -i (ln |z| + i Arg z) = Arg z. So yes, this definition makes perfect sense.

**Comment by elkins0** [comment]
See #194 geoOps.Angle for a sample implementation...

**Comment by kranich** [comment]
>Another definition that generalizes straightforwardly would be 'the principal argument of the complex number x + i y'. There it does not matter whether x and y are real or complex. But this is different, semantically.

Note that Wolfram's definition is equivalent to the above definition, which I find easier to understand. I will submit a pull request.

**Comment by kranich** [comment]
Either I am too tired, or Wolfram does not adhere to its definition. In Mathematica, I obtain

```Mathematica
In[1]:= ArcTan[-I,I]
Out[1]= (3 \[Pi])/4
In[2]:= -I Log[(-I+I I)/Abs[-I+I I]]
Out[2]= -((3 \[Pi])/4)
```

**Comment by gagern** [comment]
I vote for too tired.

    In[2]:= -I Log[(-I+I I)/Abs[-I+I I]]

That should be -I Log[(-I+I I)/Sqrt[(-I)^2 + I^2]]

I think this is really the crux here: √(*x*<sup>2</sup>+*y*<sup>2</sup>) ≠ |*x* + *iy*|. Which in turn makes this different from the implementation via the argument of *x* + *iy*, since that does indeed return -¾*π* for input (-I, I).

**Comment by kranich** [comment]
@gagern OK, let me update #227.

**Comment by gagern** [comment]
Comparing the two possible definitions, I think that the main reason to prefer Mathematica's definition over Stefan's is that sin(*ϕ*)<sup>2</sup> + cos(*ϕ*)<sup>2</sup> = 1 holds for complex *ϕ* as well, while |sin(*ϕ*) + *i* cos(*ϕ*)| ≠ 1 in general. So if `arctan2` is seen as a reversal of sin and cos, then sticking to the square root approach makes more sense.

I see that the implementation @elkins0 suggested in #194 does do this. But there it's a definition of a geometric operation, and I have some doubts that we actually want this behavior there. But that's to be discussed on that pull request, not here. Anayway, we could use [those four lines there](https://github.com/elkins0/CindyJS/blob/patch-5/src/js/libgeo/GeoOps.js#L2054-L2057) as our `arctan2` implementation.

**Comment by kranich** [comment]
> Anayway, we could use those four lines there as our arctan2 implementation.

@gagern We still need to handle the case where x = y = 0. I have rebased #227 accordingly.

**Comment by kranich** [comment]
The corresponding issue for Cinderella is [#121](https://gitlab.cinderella.de:8082/cinderella/driftin/issues/121).
