### ISSUE TITLE
default parameters for geoOps

### ISSUE THREAD

**Issue by strobelm** [CindyJS/CindyJS#229]
While playing around with the angle bisector code it came to my mind that default arguments in geoOps would be nice to have. Therefor i quickly wrote some testing code:

https://github.com/strobelm/CindyJS/tree/defaultParam

The idea is to place some default arguments to the signature like this
```
geoOps.defaultArgChecker.signature = ["P", "P=[0,0,1]"];
```

and parse these in GeoBasics. Of course the code is only for discussion and not ready to be merged. Nevertheless any comments on the approach?

**Comment by gagern** [comment]
I think that having a specific constant value as an optional argument is an unlikely case. The far more common case in my opinion would be an optional argument which when missing can be computed from the given arguments. I wouldn't want to do that in a text string encoding a CindyScript evaluation, but rather inside the implementation itself. (If that implementation were to be completely written in CindyScript, that would be a different story.) So I think we only need to tell the signature verification phase that it is OK to have `undefined` (and/or `null`?) elements in the `args` array. Then the implementation can deal with that in a way suitable to the situation at hand.
