### ISSUE TITLE
Rendering of circles is too coarse

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#238]
I just tried to export a file from Cinderella – it worked fine, but the rendering of circles is below our standards... 

<img width="584" alt="bildschirmfoto 2016-02-11 um 13 51 25" src="https://cloud.githubusercontent.com/assets/1773555/12976747/98b790b4-d0c6-11e5-8289-c116f84db02a.png">

This is how it looks in Cinderella itself:
<img width="583" alt="bildschirmfoto 2016-02-11 um 13 48 47" src="https://cloud.githubusercontent.com/assets/1773555/12976755/a522904c-d0c6-11e5-8f7d-a6c3228cdad9.png">

Browser used is Safari, latest version.

**Comment by strobelm** [comment]
Interesting, could you supply the files?

Am 11.02.2016 um 13:52 schrieb kortenkamp:
>
> I just tried to export a file from Cinderella – it worked fine, but
> the rendering of circles is below our standards...
>
> bildschirmfoto 2016-02-11 um 13 51 25
> <https://cloud.githubusercontent.com/assets/1773555/12976747/98b790b4-d0c6-11e5-8289-c116f84db02a.png>
>
> This is how it looks in Cinderella itself:
> bildschirmfoto 2016-02-11 um 13 48 47
> <https://cloud.githubusercontent.com/assets/1773555/12976755/a522904c-d0c6-11e5-8f7d-a6c3228cdad9.png>
>
> Browser used is Safari, latest version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CindyJS/CindyJS/issues/238>.
>

-- 
Michael Strobel, M.Sc.

Technische Universität München -- Zentrum Mathematik
Lehrstuhl für Geometrie und Visualisierung (M10)
Boltzmannstr. 3, 85747 Garching bei München 
https://www-m10.ma.tum.de/bin/view/Lehrstuhl/MichaelStrobel

**Comment by kortenkamp** [comment]
Unfortunately, no, as they are from a 3rd party. At least I cannot put them on the web, but I will send the .cdy to you by PM.
