### ISSUE TITLE
CindyGL and arrays of complex numbers

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#243]
CindyGL cannot guess the type of an array of complex numbers.

**Comment by montaga** [comment]
At current state CindyGL can only handle arrays consisting of exactly 2 complex numbers (~vec4 in glsl; purpose: handling Möbius transformations nicely) and 2, 3, 4 real numbers (~vec2, vec3, vec4).

This won't change until a generic type system for CindyGL is implemented, which is a rather faraway bigger milestone.

**Comment by kranich** [comment]
@montaga OK. Then just let's leave this open as a reminder for the time being.

**Comment by montaga** [comment]
This is fixed by https://github.com/CindyJS/CindyJS/pull/490
