### ISSUE TITLE
Pinned circles can change their radius

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#254]
I exported some circles with radius from Cinderella. I pinned them such that the radius cannot be changed with the mouse. This works in Cinderella, however in CindyJS I can change them.

Could also be a problem with the export from Cinderella forgetting the "pinned" attribute.

**Comment by strobelm** [comment]
Hi,

i just tried to reproduce the bug. The pin attribute is exported and working properly, have you tried a current build of Cinderella?

**Comment by kortenkamp** [comment]
I attach a file that exhibits that problem. The circles cannot be changed in Cinderella, but in CindyJS. I have no idea why.
[AntiPropTacho.cdy.zip](https://github.com/CindyJS/CindyJS/files/138339/AntiPropTacho.cdy.zip)

**Comment by strobelm** [comment]
I identified the problem: the example fixed the circle radius by the circle.radius accessor. It will be fixed as soon we implemented #224.

**Comment by kranich** [comment]
Closed via #293.
