### ISSUE TITLE
roots may return undefined

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#270]
It has come to my attention that the `roots` operator may, under some circumstances, contain `undefined` values in its resulting list. Example (found while experimenting with drawing conics):

    roots([0,0,0,0,1])_3 + 0

The list returned by this is `[0, 0, undefined, undefined]`, with the first two elements being normal CindyJS complex numbers, the latter two being raw JavaScript undefined values. We should *never* be returning those from functions that can be called from CindyScript, as they will easily cause exceptions and we are not exception safe. The `+ 0` demonstrates such an exception.

If you can't think of a better solution, a quick hack would be either removing all unset list elements, or replacing them by `nada`. The correct solution in this particular case would of course be to return some more zeros.

**Comment by kranich** [comment]
@gagern Stupid mistake. Fixed in #271.
