### ISSUE TITLE
Fuzzy comparison threshold

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#276]
Cinderella uses 10<sup>−10</sup> as the threshold for fuzzy comparisons, but CindyJS uses `CSNumber.eps` which is defined to be 10<sup>−7</sup>. We should do one of the following:

1. Set `CSNumber.eps = 1e-10`
2. Use a different constant for fuzzy comparisons
3. Adapt the documentation to state the difference

I see no reason to introduce avoidable divergence as the third approach does, so I'd go with one of the former. Of these, 2. would have less impact on other things, but there might in fact be other things affected by that same constant, leading to other discrepancies between Cinderella and CindyJS. So we probably should investigate where this constant is used in both projects, and see whether matching the definitions would make the behavior more alike.

**Comment by elkins0** [comment]
@gagern: In [CSNumber.js](https://github.com/CindyJS/CindyJS/blob/master/src/js/libcs/CSNumber.js), on line 288 the value is 1e-7:
```javascript
CSNumber.eps = 0.0000001;
```
then notice that the value is then is overwritten on line 506 with 1e-10:
```javascript
CSNumber.eps = 0.0000000001;
```
So the value is already the way you wish it to be.

**Comment by gagern** [comment]
@elkins0, thanks for reminding me, I forgot about that!
