### ISSUE TITLE
Global Interface.js for plugins

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#278]
I think that most plugins can profit from the type coercion functions defined in [plugins/cindy3d/src/js/Interface.js](https://github.com/CindyJS/CindyJS/blob/master/plugins/cindy3d/src/js/Interface.js).

This file is already reused by CindyGL.

Maybe we should move it from Cindy3D to a more global position in [plugins/](https://github.com/CindyJS/CindyJS/blob/master/plugins/)?

**Comment by gagern** [comment]
I'm not sure how I feel about this. On the one hand, I'm all for [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) code without duplications. On the other hand, I personally consider this code an integral part of Cindy3D, and want to be able to change this without any concerns for backward compatibility or effects on other plugins.

If CindyGL is essentially using the same file, I'd be happy to share the code with that. But I'd like to make it clear (perhaps via a suitable README in that directory) that this file is *not* part of the public CindyJS API, that it is subject to change without warning. And if at any point I feel like changing something in a way that might cause problems for CindyGL, I'd reserve the right to go back to my own copy again. That would allow us to share the common code now without getting teid down by compatibility obligations in the future.

Cc @montaga.

**Comment by kranich** [comment]
@gagern In that case, I would leave everything as is. CindyGL and other plugins include the file from Cindy3D sources in their list of sources, at their own risk.

If there are incompatible changes in the future, it would be nice to copy the original file for the plugins, lest we should break the plugins.

**Comment by gagern** [comment]
Agreed.
