### ISSUE TITLE
Default color of drawn points

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#298]
In Cinderella, `draw([0,0])` yields a purely green point at the origin. In CindyJS, the point is yellow per default (see [GeoState.js#L7](https://github.com/CindyJS/CindyJS/blob/master/src/js/libgeo/GeoState.js#L7)). Do we want to change this?

**Comment by kranich** [comment]
Does this setting belong in GeoState.js anyway? I would expect it in Render2D.js.

**Comment by kortenkamp** [comment]
yes, please change it (or we have to make sure that this is covered in Cinderella export)

**Comment by kranich** [comment]
@gagern Since the code for `handleModifs` and `drawpoint` in Render2D.js is yours, could you please take care of the issue?
