### ISSUE TITLE
Attach user properties to lists

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#32]
_(Manually migrated from GitLab issue 11 reported by @kortenkamp)_

In Classic Cindy it is possible to attach properties to lists, i.e. you can write

```
x=[];
x:"Test"=100;
```

In particular, this makes it possible to do a call by reference:

```
f(l):=(forall(l:"list",err(#));(l:"list")_2="B";);
x=[];
x:"list"=["a","b","c"];
f(x);
err(x:"list");
```

results in:

```
# ==> a 
# ==> b 
# ==> c 
 ==> [a,B,c] 
```

This is currently not supported by CindyJS. Please support it. ;-)

---

_(Comment originally by @gagern)_

@richter, do we want that feature in its current Cinderella form? In my opinion it's one of the more poorely designed features of CindyScript, since it mixes various unrelated concepts: the concept of a sequence/list/array type, that of a dictionary, and that of a by-reference entity type. It also breaks the clean by-value semantics we heve everywhere else, in ways which aren't clearly documented as far as I know.

For the mapping type, I'd either take the approach of classical programming languages and introduce a mapping-only type, or I'd follow Python and allow any value to carry properties. To make this fit in with by-value semantics and copy-on-write, I'd say `x:"foo"="bar"` should be the same as `x = withProperty(x, "foo", "bar")` for some hypothetical `withProperty` function which returns a new value which is equal to its first argument except for that added property. So if I did `y=x` before that line, then `y` still won't have that extra property, since it was added to `x` later on.

To achieve by-value operations, I'd take a look at ML and its derivatives. They have an explicit reference type. So a reference is an object, similar to a high-level pointer, and passing a reference around is distinct from changing the value the reference refers to. The latter has a separate syntax (`:=` in ML) since normal assignment just assigns the reference itself.

If you want to take one of these approaches, we can work out the details, particularly with respect to syntax. Having properties for arbitrary values should be possible in a backwards-compatible fashion. The reference handling would be more difficult.

Is there enough code around using such user properties to warrant a layer for backwards compatibility, or can we manually port the affected code once we have a cleaner feature specification and implementation? Even if we want a compatibility mode, I think I'd rather have a clean set of features in place up front, and then build the compatibility layer on that. Unless you insist that the current behavior in Cinderella will be the only officially supported way for the foreseeable future, of course.

---

_(Comment originally by @kortenkamp)_

We definitely need this for backwards compatibility… but I wouldn't mind a redesign.

Actually I think that the only objects in Cinderella should be things that are visible in the list of objects (that is, PGElements). These should have the option to add properties. Lists can do that currently, but I am not sure how many people are really using that (probably only @richter).

I am currently implementing CSObjects (that subclass PGElements), those appear in the PGElements-list and can carry properties, of course.

---

_(Comment originally by @gagern)_

Looking at Cinderella, the interface in question is `UserData`, which is implemented by `PGElement` and `CEnum`. `PGCSObject` inherits from `PGElement` via `PGVisible`. So Cinderella is using two distinct implementations to implement this feature, and CindyJS might likewise use different internal representations. `OpGetUserField` operates on these. But it also operates on `CObject`, which for some reason doesn't implement that interface (it should be possible to change that, eliminating some dupliucate code in the process). I hadn't known about `CObject` before, is that going to be officially supported, or is that just for experiments so far?

Translating this to CindyJS, the Cinderella `PGElement` would correspond to an element el of the `csgeo.gslp` list. That's an object with properties `name` and `type`, often `pos` and `homog` and other stuff like that as well. We could add a property `userData` easily. The geometric objects persist, are identified by name, and cannot be copied. So the question of correct copy-on-write behavior doesn't arise. The keys are always converted to strings, which agrees nicely with objects in JavaScript. We might however want to prefix those strings with some fixed prefix in order to avoid collisions with predefined (i.e. inherited) properties.

`CEnum` on the other hand corresponds to a `{ctype:'list', value:[…]}` object CindyJS. `OpTake` in Cinderella modifies its lists directly, while CindyJS performs a copy-on-write. `Variable.setValue(…)` in Cinderella does copy, and that `CEnum.copy()` copies user data as well. Only shallow, though. Looking at the interplay between assignments and copying, I realize that this is an evil mix of semantics:

```
a=[1,2]; a:"x"=[3,4]; b=a; (b:"x")_1=5; err(a:"x"); // => [5,4]
a=[1,2]; b=[0,0]; b_1=a; b_2=a ; b_1_1=3; err(b);   // => [[3,2],[3,2]]
a=[1,2]; b=[          a,     a]; b_1_1=3; err(b);   // => [[3,2],[1,2]]
```

I consider this to be highly unintuitive! I refuse to implement these exact semantics (unless someone can provide a very good reason why they should be like this). The copy on write in CindyJS should lead to clean by-value semantics in all locations (anything else is a bug). In CindyJS the second line, too, results in `[[3,2],[1,2]]`.

But that's just an observation made along the way. Observing that value versus reference semantics are already different, it doesn't make too much sense to reproduce user properties strictly along the lines of Cinderella's semantics. The important thing is making classical use cases work. But what are these? I've known one student who (iirc) used user properties to build cyclic data structures. Which doesn't integrate well with by-value semantics. I considered their use of properties a hack at that time, and would prefer a cleaner setup which makes references explicit, as discussed above.

So while we can and probably should implement properties for geometric elements, having user properties for lists should merit some more discussion, and having them for objects (á la `CObject`) should have some discussion whether we want objects in CindyJS in the first place, and how to implement these. If we extend the set of possible `ctype` settings, then we'll have to go over the code and identify locations which perform case distinctions based on an exhaustive enumeration of possible types. If we want a `reference` type as well, we might change these locations adding both `object` and `reference` in a single modification.

**Comment by kortenkamp** [comment]
Actually, yes, we want this feature. Has been implemented now in v0.8.12, more than 6 years later…
