### ISSUE TITLE
Rename createCindy to CindyJS

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#322]
It is customary that a package exports a single symbol, which is named as the package itself and which serves as the namespace containing all their public API of the module. In CindyJS the names are different: the package called `CindyJS` exports a symbol `createCindy`. It would be good to rename `createCindy` to `CindyJS`, while maintaining the former for a while for the sake of backwards compatibility. Probably with a deprecation notice to the web developer console.

**Comment by strobelm** [comment]
Resolved by #348.
