### ISSUE TITLE
Do not draw segments beyond boundary of canvas

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#332]
Segments should be clipped to canvas in `Render2D.drawsegcore`. This is a follow up of #292.

Does anyone have an idea how to achieve this without too many case distinctions?

**Comment by elkins0** [comment]
Caution -- The clipping window first needs to be expanded by the line width times sqrt(0.5) in all directions!
Function withinClipWindow is to return true for the boundaries as well as inside them.
Function onSegment is to be true inclusive of el.startpos and el.endpos but not [0,0,0].

Here is my idea in pseudo code:
```javascript
//At least something like this or its complement I think...
function onSegment(el, testPoint) {
    var lt = CSNumber._helper.isLessThan;
    var zero = CSNumber.zero;
    return lt(List.scalproduct(el.homog, testPoint.homog), zero) !== 
             (lt(el.homog.value[2], zero) === lt(el.testPoint.value[2], zero));
}

function clipSegment(el) {
    //Step 1 - Are both segment's points inside the clipping window?
    var startInside = withinClipWindow(el.startpos);
    var endInside = withinClipWindow(el.endpos);
    if (startInside && endInside) return [el.startpos, el.endpos];

    //Step 2 - Clip the line of the segment 
    var clipPoints = clipLine(el.homog);
    if (clipPoints === []) return []; // Nothing inside the clipping window

    // Step 3 - select points
    var res = [];
    if (onSegment(el, clipPoints[0])) res.push(clipPoints[0]);
    if (onSegment(el, clipPoints[1])) res.push(clipPoints[1]);
    if (res.length === 1) {
        if (startInside) res.push(el.startpos);
        if (endInside) res.push(el.endpos);
    }
    if (res.length !== 2 && res.length !== 0) console.log("Assertion: The code has a logic error");
    return res;
}
```

**Comment by kranich** [comment]
@elkins0 Thanks, your proposal looks reasonable. Do you want to implement it yourself or should I give it a go?

**Comment by kranich** [comment]
@elkins0 You mean `sqrt(2)`, not `sqrt(0.5)`, right?

**Comment by elkins0** [comment]
@kranich Please do give it a go. I just wanted to outline one possible approach. You are in a better position to determine the requirements. On a segment with line width there are further considerations. The first of which is, is it assumed that canvas window clipping will take care of the corners of angled lines with width that stick out past the boundary? If not, a conversion into a filled polygon would be required. The assumption is that the butt cap style will be used. However the overhang parameter which can be positive or negative must also be accounted for by computing different endpoints. Also for endpoints outside of the clipping window yet close enough to the clipping window where only a corner of the width protrudes inward must also include more than just the endpoint to give the canvas routines something to determine the direction.
![segmentclipping](https://cloud.githubusercontent.com/assets/15895776/14839997/f308a8a8-0bec-11e6-98dd-98f6f6cef7ba.png)
