### ISSUE TITLE
Closure Compiler v20160713

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#407]
The jar downloaded from dl.google.com now includes the version number in its filename (closure-compiler-v20160713.jar).

We should adapt our build process accordingly, sooner or later.

**Comment by gagern** [comment]
Just for discussion: theoretically it was possible so far to pass `closure_version=…` on the command line to run a build with a compiler version other than the default. Should we support this across the rename, or is nobody using that anyway? I personally don't see much use to switch versions like this, but I thought I'd mention it.

**Comment by kranich** [comment]
@gagern I was not aware of this feature. I do not think it is necessary to support it. If you want to test another version, you can edit `make/Settings.js` as well.
