### ISSUE TITLE
setTimeout in current Cindy.js

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#427]
I just tried to update all my Cindy.js files to the current version. I get the following error:
`Called undefined function settimeout (as settimeout$2)`

Note that I, of course, called the function as `setTimeout(2, ...);`

Something seems to be wrong with capitals in function names...

**Comment by strobelm** [comment]
Hi Bernhard, could you provide a (minimal) example? I'll have a look.

**Comment by BernhardWerner** [comment]
Sure:

init-script:
`test = false;
setTimeout(3, test = true); `

draw-script:
`drawtext((0,0), test);`
