### ISSUE TITLE
segments on physics objects seem to be broken

### ISSUE THREAD

**Issue by strobelm** [CindyJS/CindyJS#48]
Hi, just a quick notice. It seems that segments on objects influenced by the physics engine are broken. For example look at examples/35_Springs.html in the current master. I'll try to bisect the problem tomorrow.

![springs](https://cloud.githubusercontent.com/assets/14185442/10801722/101ed484-7db9-11e5-9792-dde1f34344bd.png)

**Comment by strobelm** [comment]
After some bisection i found the faulty commit: ee4954cdd4ac278c12778119ca187c5df585e474 Support TrInverse, TransformL and TransformS.

The actual problem is that el.startpos and el.endpos never get updated for segments. When we switch back to the coordinates of csgeo the drawing works just fine:

https://github.com/strobelm/CindyJS/commit/80416e06eb03301ed6f2f14a208575ad36afdd58

Probably this is not the fix we want (rather an update call for segments). @gagern: do you have an idea where the update should take place?

**Comment by gagern** [comment]
Thanks for tracking this down, even if it identifies me as the culprit. Although I don't understand the problem yet, since [these lines](https://github.com/CindyJS/CindyJS/blob/ee4954cdd4ac278c12778119ca187c5df585e474/src/js/libgeo/GeoOps.js#L64-L65) look as if `geoOps.Segment.updatePosition` *should*  be updating these properties.

**Comment by strobelm** [comment]
No hard feelings here ;-). I was also wondering why this does not see an update even though the updatePosition is well defined, my browser tells me that the function is never called though. It is unclear to me where the call should take place, therefor it would be nice to know where the canonical place is.

**Comment by kortenkamp** [comment]
Seems to me that there is something crucial is missing in the update loop for elements. After a move (by touch or mouse), all dependent elements must be updated. After a move through physics, the same is true, of course.

**Comment by gagern** [comment]
Yes, there is something very wrong here. Will have a closer look after lunch.
