### ISSUE TITLE
Comments are shown in the header

### ISSUE THREAD

**Issue by masatakakaneko** [CindyJS/CindyJS#481]
In some cases, there seems to appear comments at the header of html output.

**Comment by masatakakaneko** [comment]
[sample5.html.zip](https://github.com/CindyJS/CindyJS/files/481716/sample5.html.zip)

**Comment by kortenkamp** [comment]
I can confirm the report of @masatakakaneko – a comment in CindyScript will somehow trickle through to the HTML and will be rendered as //. I attach a screenshot of sample5.html.
![bildschirmfoto 2016-09-20 um 15 11 18](https://cloud.githubusercontent.com/assets/1773555/18659288/94f168a6-7f44-11e6-8d7a-026d325312bb.png)

**Comment by kortenkamp** [comment]
We just realized that there was another place that contained `//`, so these comments were just a typo.
