### ISSUE TITLE
Inconsistent default line widths

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#50]
We have two different default line widths.

One is defined using `csport.drawingstate.linesize` and [defaults to 1.0](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libgeo/GeoState.js#L13). It ends up in the [`Render2D.lsize`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/Render2D.js#L46) setting. This is used for segment drawing. Other pieces of code set `csctx.lineWidth` directly, namely

* [drawarc defaults to `4/2.5`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L170-L175),
* [drawcircle defaults to `4/2.5`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L318-L321),
* [drawconic defaults to `4/2.5`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L405-L410) ([reused](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L594) in nested function),
* [polygon defaults to `4/2.5`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L819-L822),
* [plot uses `Render2D.lsize`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L1058) so it's consistent with segments,
* [plotX hardcoded to 1](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#L1265).

I'm not sure about `plotX` (perhaps this should even be removed?), but the difference between `1` and `4/2.5=1.6` is confusing, as is the fact that the latter isn't affected by the [`defaultAppearance`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/OpDrawing.js#user-content-defaultappearance) option to the `createCindy` call. This should be unified.

**Comment by kortenkamp** [comment]
I am quite sure that this is connected to #31 - people creating larger lines to remove the blurring that occurs due to sub-pixel rendering.

**Comment by gagern** [comment]
@kortenkamp: Larger lines to remove blurring would make sense if the line width for straight lines were larger than that for curved lines. The fact that it's the other way round suggests otherwise. But it might be that the curved lines were drawn wider to compensate for the fact that the blurred lines appear wider than they were defined. So #31 might still be to blame. If so, I'd say we should fix #31 and stick to consistent defaults here. If my theory above is correct, then someone perceived the majority of lines as being 1.6px wide due to blurring. In which case we'd minimize breakage if we declare 1.6 as the new default line width after unifying all the occurrences.
