### ISSUE TITLE
Clean up status of convexhull3d

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#51]
Currently, the [`convexhull3d` operator](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/Operators.js#L3595) only works if it can call an external function `convexhull` [defined](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/java/cindyjs/quickhull3d/JavaScriptBindings.java#L20-L21) by the GWT-compiled `quickhull3d` code. So that code has to be loaded for the operator to work; otherwise an exception will be thrown.

Possible solutions include

1. Load the code of `quickhull3d` unconditionally before starting the first CindyJS instance
2. Make `quickhull3d` into a regular plugin, and detect the need for it in Cinderella upon export
3. Load code on demand if a given CindyJS instance seems to need it, before starting that instance
4. Port code to JavaScript, assuming that the result will be easier to handle than the GWT-compiled code

**Comment by kortenkamp** [comment]
Is this really a bug? I suggest to load the code as suggested in (1) and later do (4).

**Comment by gagern** [comment]
The current state of affairs is a bug, since no CindyScript operation should be throwing exceptions. The CindyScript evaluator is not designed in an exception-safe way. My main concern with (1) is the fact that GWT-compiled code gets loaded asynchroneously, which might be problematic for some applications.

**Comment by kortenkamp** [comment]
Ok, then maybe (3) then (4) is better? The load on demand code could easily (?) be created as a function `convexhull` that just checks whether the external `convexhull` is available and loads the GWT code then. 
The question mark behind easily is caused by my own inability to write such JS code.

**Comment by gagern** [comment]
Unfortunately it's not that simple: loading additional code happens asynchroneously, so we can't have that function wait till the code is available. It has to return something. We could have it return `nada` and trigger a repaint once the code is there. But if the output of `convexhull3d` is used anywhere to initialize persistent data structures, particularly during init, then this will still very likely lead to incorrect behavior. Instead we'd have to analyze the script first, see what functions it calls, then act on that.

One could extend the [`funct`](https://github.com/CindyJS/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/libcs/Parser.js#L433) function of the parser to maintain a list of function names (and arities) encountered while parsing the scripts, then act on that. People invoking `convexhull3d` from `cdy.evokeCS` would still be in trouble, but I guess that's rather unlikely.

**Comment by kortenkamp** [comment]
Too bad. I thought that maybe one could just wait for loading (even if that's done asynchronously) and then return the output.

**Comment by gagern** [comment]
For that the interpreter would have to be written in a completely different way, not using nested function calls in JavaScript but maintaining its own instruction pointer instead. That's not going to happen any time soon.

I just had a stab at automatically loading code on demand, see https://github.com/gagern/CindyJS/commit/cc2799a2392c64aecfd6eb94e1efb65948fc75a3. If `convexhull3d` were contained in a single JavaScript file, this should work. But as I said, GWT loads its scripts asynchroneously, so I'll either have to adapt the already hackish [code for GWT module startup recognition](https://github.com/gagern/CindyJS/blob/57a564d89124df6d86f605272bc91740fb2c2348/src/js/Head.js#L46-L58) or come up with some cleaner solution where the module actively reports back that it has been loaded successfully.

Come to think of it, that might be a reasonable approach: make convexhull3d into a plugin, auto-detect the fact that it's required and trigger it getting loaded, and once it got loaded and registers itself, then continue starting any instance that has been waiting on that module.

**Comment by kortenkamp** [comment]
Your last remark sounds indeed reasonable!
