### ISSUE TITLE
dash type, colour and perhaps other attributes

### ISSUE THREAD

**Issue by JHM27** [CindyJS/CindyJS#524]
Do these work yet in CindyJS?

They don't seem to work for me!

**Comment by gagern** [comment]
http://cindyjs.org/examples/108_DashType.html demonstrates some dashed lines, and many of the examples use colored lines. Even export from Cinderella works, with the caveat of #109 still being open. Please make sure you're using [the latest Cinderella beta version](http://beta.cinderella.de/public/), and attach the exported HTML file as well as the CDY file (probably renamed to `*.zip` to keep GitHub happy) so we can have a look at them.
