### ISSUE TITLE
Complex Curves examples fail on MacBook

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#534]
This is in continuation of https://github.com/CindyJS/CindyJS/pull/521#issuecomment-259459037. As stated there, the Complex Curves examples currently fail for me in both Firefox and Chrome on macOS Sierra with a MacBook Pro 2015. No messages are printed to console. The webglreport.com report in Chrome reads thus:

```
Platform:	MacIntel
Browser User Agent:	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Intel Inc.
Unmasked Renderer:	Intel(R) Iris(TM) Graphics 6100
Antialiasing:	Available
ANGLE:	No
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	1024
Max Vertex Texture Image Units:	16
Max Varying Vectors:	15
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range:	[1, 7]
Aliased Point Size Range:	[1, 255]
Fragment Shader
Max Fragment Uniform Vectors:	1024
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	16384
Max Viewport Dimensions:	[16384, 16384]
Textures
Max Texture Size:	16384
Max Cube Map Texture Size:	16384
Max Combined Texture Image Units:	16
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
```

Hope this helps.

**Comment by gagern** [comment]
We might be looking at multiple causes here: http://complexcurves.org/#Circle renders correctly in Firefox, but not in Chrome. So this appears to be in part specific to the plugin.

**Comment by kranich** [comment]
@gagern Please try http://complexcurves.org/#Circle?cached=0 in a new window. Does Chrome report anything for  http://complexcurves.org/#Circle?

Please post webglreport.com output for Firefox on Mac OS and for Safari.

**Comment by kranich** [comment]
The problem seems to be that Mac OS does not properly support reading pixels from floating point textures. It seems to be controversial whether this feature is part of `OES_texture_float` or `WEBGL_color_buffer_float`. 

Chrome on Linux does not report support for `WEBGL_color_buffer_float`, but nevertheless supports reading pixels from floating point textures. Firefox on Linux exposes the extension and supports reading pixels from floating point textures. Firefox on Android does not expose the extension and does not support reading pixels from floating point textures.

What a mess!

**Comment by kranich** [comment]
I will try to query [`IMPLEMENTATION_COLOR_READ_TYPE`](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14.12) to detect support.

**Comment by gagern** [comment]
If everything else fails, could you just do a trial run: render some known content to some off-screen canvas and see whether the result is consistent with support for reading pixels or not?

**Comment by kranich** [comment]
I have just pushed https://github.com/CindyJS/CindyJS/pull/521/commits/fb89a69edb0c937cdae8dec53bf52d578bb488ad. Please try again with Firefox and Chrome on Mac OS. Now at least an error should be shown in the console.

I will continue to try to improve portability but I am not too optimistic.

**Comment by kranich** [comment]
I think I have come up with a workaround. May need a few days to implement it.

**Comment by kranich** [comment]
@gagern Found out that workaround only partly solves the issue. Some platforms do not support rendering to float textures even with `OES_texture_float` support.

Please test if error is now printed on console. Should we alert instead?

With proper error reporting in place, I would merge #521 and then continue to try improve portability.

**Comment by gagern** [comment]
> Please test if error is now printed on console. Should we alert instead?

Yes, I see the error message here. I think an alert would be better, as few users will watch the error console, and as a merely black widget area will reflect poorly on the project. (I think we should be alerting in many more cases, but that's something for a different PR.)

> I would merge #521 and then continue to try improve portability.

Fine by me, at least if you also had a look at my changes to the build process, and feel comfortable co-maintaining that aspect. Otherwise I'd like an opinion from @strobelm to ensure I didn't do something too exotic in #521.

**Comment by kranich** [comment]
Superseded by https://github.com/kranich/ComplexCurves/issues/1.
