### ISSUE TITLE
No mention of cindyjs.org in README.md

### ISSUE THREAD

**Issue by kranich** [CindyJS/CindyJS#609]
We should mention https://cindyjs.org in [README.md](https://github.com/CindyJS/CindyJS/blob/master/README.md).

Particularly, I think that our [showcase gallery](https://cindyjs.org/gallery/main/) and our [thematically sorted gallery](https://cindyjs.org/gallery/) should be highlighted as a source of examples instead of or in addition to [Science to Touch](http://science-to-touch.com/CJS/).

**Comment by kranich** [comment]
What do you think?

**Comment by kranich** [comment]
Plus I think it would be great if the examples were referred to in the first paragraph, so that they are visible in the teaser of README.md shown in the mobile version of GitHub (before one needs to click on [View all of README.md](https://github.com/CindyJS/CindyJS))./blob/master/README.md

**Comment by gagern** [comment]
:+1: for having the official page included, and the gallery there replace the one on Science to Touch.

Do you have details on how the README gets cut? Technically that first bold line would be the first paragraph, but we get the paragraph after that included as well. Is it everything up to the first headline? In that case, adding it as a separate paragraph in addition to the existing ones would be nice on mobile. On desktops it might feel weird that there are examples mentioned before the Examples section. So perhaps we should leave the examples to that section, and only add a general note indicating that end user information can be found at cindyjs.org.

**Comment by kranich** [comment]
:+1: for adding a general note indicating that end user information can be found at cindyjs.org. Maybe we can also refer to the examples section?

On my smartphone, the teaser currently stops after "but also from various other fields.". Is it the same on tablets?

I have no idea how the break is determined, neither could I find any information in the GitHub documentation. So it's probably trial and error. :-/
