### ISSUE TITLE
Clean up timer handling

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#64]
We have different pieces of code handling timed events for animation and mouse updates.

The currently active form uses [`Timer.js`](https://github.com/CindyJS/CindyJS/blob/33416e4f7f809f35cbbf5ac095fffd6f2fecc81c/src/js/Timer.js), a modified version of the D3 timer. It has quite a bit of code complexity, since it aims at supporting multiple scheduled events using a single timer instance. The only thing we do is run events on a regular basis with [minimal](https://github.com/CindyJS/CindyJS/blob/33416e4f7f809f35cbbf5ac095fffd6f2fecc81c/src/js/Timer.js#L52) delay. This leads to a call to [`d3_timer_frame`](https://github.com/CindyJS/CindyJS/blob/33416e4f7f809f35cbbf5ac095fffd6f2fecc81c/src/js/Timer.js#L86) which is essentially an [alias for `requestAnimationFrame`](https://github.com/CindyJS/CindyJS/blob/33416e4f7f809f35cbbf5ac095fffd6f2fecc81c/src/js/Timer.js#L45-L47) these days [except on IE < 10](http://caniuse.com/#feat=requestanimationframe). So most of the machinery in that file is not being used by our code.

As an alternative, we have our own definition called [`requestAnimFrame`](https://github.com/CindyJS/CindyJS/blob/33416e4f7f809f35cbbf5ac095fffd6f2fecc81c/src/js/Events.js#L222-L231) which is used by [`update`](https://github.com/CindyJS/CindyJS/blob/33416e4f7f809f35cbbf5ac095fffd6f2fecc81c/src/js/Events.js#L266-L271). But `update` itself doesn't seem to be used anywhere at all. So that code path, which would seem much simpler, isn't being used at all.

I think we should have another stab at building and testing our own timer implementation based on this `requestAnimFrame`. If this works, we could get rid of the D3 timer code. If not, we would hopefully have a better idea of *why* we need more complexity. And either extend our own approach, or remove our own code and accept that this complexity is (still?) needed.

**Comment by kranich** [comment]
I noticed that a newer version of D3 timer is also available as a separate project at https://github.com/d3/d3-timer. Might be interesting to compare it to our current approach and the above planned approach.

**Comment by gagern** [comment]
#386 has a recent attempt to eliminate the use of the D3 timer, currently pending review.

**Comment by gagern** [comment]
Fixed by #386.
