### ISSUE TITLE
use multiple 3d canvases

### ISSUE THREAD

**Issue by mo271** [CindyJS/CindyJS#647]
While it is no problem to run multiple canvases with different names in `CindyJS({canvasname:"CSCanvas",...`, I am having trouble doing the same thing when using Cindy3d. 
Then it seems that there it is only possible to have one DOM element canvas with the id `"canvas3D"`. 

Is this correct, or is there a way to have two canvases with the torus [Torus.html](https://cindyjs.org/examples/cindy3d/15_Torus.html) display next to each other?

If this doesn't work: should this be a feature or is there a reason why this would be not allowed?

**Comment by montaga** [comment]
It is possible to have multiple canvases in Cindy3D, however it is not documented yet (And maybe the definitions might change in further versions...)
Whenever you use `begin3d` you can use a modifier `name` to specify the id of the canvas. For instance,
`
begin3d(name->"Cindy3D-2");
...
end3d();
`
will render to `<canvas id="Cindy3D-2" width="632" height="452"></canvas>`

Using several such blocks using different `name` modifiers you can have multiple 3D canvases displayed next to each.

Hope this helps!
