### ISSUE TITLE
CindyGL random generator  is not good enough

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#662]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/1773555/40907085-fb117aee-67e2-11e8-9366-e239503bd2f8.png">

This is an image generated by 

`colorplot(L,R,sampleindices, i=random()*256*256;[mod(i / 256, 256),mod(i,256),0]/256);`

that clearly shows artifacts.

**Comment by kortenkamp** [comment]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/1773555/40907276-99bab818-67e3-11e8-9011-55ba3857988c.png">

Just another one to show how bad it is.

**Comment by montaga** [comment]
This should be fixed with #664 and #665
