### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#670]
I tried to build CindyJS on Windows 10 using cygwin. The make process fails as follows:
 
```
ulli@DESKTOP-FIE79QB /cygdrive/c/Users/ulli/WebstormProjects/CindyJS
$ make
node make/index.js build=debug
Running npm install to make sure we have all dependencies
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> cindyjs@0.0.1 prepublish C:\Users\ulli\WebstormProjects\CindyJS
> $NODE make/index.js call_npm=false parallel=true build=release all

Der Befehl "$NODE" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cindyjs@0.0.1 prepublish: `$NODE make/index.js call_npm=false parallel=true build=release all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cindyjs@0.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ulli\AppData\Roaming\npm-cache\_logs\2018-06-19T12_26_26_665Z-debug.log
C:\Users\ulli\WebstormProjects\CindyJS\make\index.js:70
            throw Error("npm terminated with code " + code);
            ^

Error: npm terminated with code 1
    at ChildProcess.<anonymous> (C:\Users\ulli\WebstormProjects\CindyJS\make\index.js:70:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
make: *** [Makefile:2: all] Fehler 1

ulli@DESKTOP-FIE79QB /cygdrive/c/Users/ulli/WebstormProjects/CindyJS
$
```

**Comment by strobelm** [comment]
It should be unnecessary to use cygwin. A working nodejs installation on windows should be sufficient. Any particular reason why cygwin is used?

**Comment by kortenkamp** [comment]
Because wasn’t sure how to build at all. As I knew that there is a plain Makefile I thought it is a good idea to run make.  And as I needed git anyway, installing Cygwin seemed like a good idea. I’ll try to get rid of it and try again.

**Comment by strobelm** [comment]
``node make build=release`` should (hopefully) work out of the box if nodejs is working.

**Comment by kortenkamp** [comment]
Nope. Same Problem with working Node.js in cmd.exe:

```
C:\Users\ulli\WebstormProjects\CindyJS>node make build=release
Running npm install to make sure we have all dependencies
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> cindyjs@0.0.1 prepublish C:\Users\ulli\WebstormProjects\CindyJS
> $NODE make/index.js call_npm=false parallel=true build=release all

Der Befehl "$NODE" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cindyjs@0.0.1 prepublish: `$NODE make/index.js call_npm=false parallel=true build=release all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cindyjs@0.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ulli\AppData\Roaming\npm-cache\_logs\2018-06-19T13_00_52_763Z-debug.log
C:\Users\ulli\WebstormProjects\CindyJS\make\index.js:70
            throw Error("npm terminated with code " + code);
            ^

Error: npm terminated with code 1
    at ChildProcess.<anonymous> (C:\Users\ulli\WebstormProjects\CindyJS\make\index.js:70:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

C:\Users\ulli\WebstormProjects\CindyJS>
```

**Comment by kranich** [comment]
You can add "NODE=node " without the quotes in front of whatever command you are using. Or run "export NODE=node" before the first command.

Best regards,

Stefan 

Am 19. Juni 2018 15:04:06 MESZ schrieb kortenkamp <notifications@github.com>:
>Nope. Same Problem with working Node.js in cmd.exe:
>
>```
>C:\Users\ulli\WebstormProjects\CindyJS>node make build=release
>Running npm install to make sure we have all dependencies
>npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are
>deprecated.
>npm WARN prepublish-on-install Use `prepare` for build steps and
>`prepublishOnly` for upload-only.
>npm WARN prepublish-on-install See the deprecation note in `npm help
>scripts` for more information.
>
>> cindyjs@0.0.1 prepublish C:\Users\ulli\WebstormProjects\CindyJS
>> $NODE make/index.js call_npm=false parallel=true build=release all
>
>Der Befehl "$NODE" ist entweder falsch geschrieben oder
>konnte nicht gefunden werden.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! cindyjs@0.0.1 prepublish: `$NODE make/index.js call_npm=false
>parallel=true build=release all`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the cindyjs@0.0.1 prepublish script.
>npm ERR! This is probably not a problem with npm. There is likely
>additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!    
>C:\Users\ulli\AppData\Roaming\npm-cache\_logs\2018-06-19T13_00_52_763Z-debug.log
>C:\Users\ulli\WebstormProjects\CindyJS\make\index.js:70
>            throw Error("npm terminated with code " + code);
>            ^
>
>Error: npm terminated with code 1
>at ChildProcess.<anonymous>
>(C:\Users\ulli\WebstormProjects\CindyJS\make\index.js:70:19)
>    at emitTwo (events.js:126:13)
>    at ChildProcess.emit (events.js:214:7)
>at Process.ChildProcess._handle.onexit
>(internal/child_process.js:198:12)
>
>C:\Users\ulli\WebstormProjects\CindyJS>
>```

-- 
Stefan Kranich
Admiralbogen 51
80939 München

Telefon: +49 89 46223879
Mobil: +49 176 45535527

**Comment by kortenkamp** [comment]
Well, yes. I can also add call_npm=false to my call to node make. But this will just work around the bug that's in the build process. I could not find the prepublish script that is causing that, otherwise I'd fix it.

**Comment by kranich** [comment]
https://github.com/CindyJS/CindyJS/blob/master/package.json#L37

I think we can try to replace $NODE by node.


Am 19. Juni 2018 15:55:43 MESZ schrieb kortenkamp <notifications@github.com>:
>Well, yes. I can also add call_npm=false to my call to node make. But
>this will just work around the bug that's in the build process. I could
>not find the prepublish script that is causing that, otherwise I'd fix
>it.

-- 
Stefan Kranich
Admiralbogen 51
80939 München

Telefon: +49 89 46223879
Mobil: +49 176 45535527
