### ISSUE TITLE
Is "csmove" called if there is no move/interaction? csmove → println()

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#714]
I thought that the stage only updates if there is a mouse move / interaction, also mentioned here https://github.com/CindyJS/CindyJS/pull/65

However, if I do:

		<script id="csmove" type="text/x-cindyscript">
			println("Test");
		</script>

It is continously printed in the console. Expected: It only prints if there is a mouse movement/interaction.

**Comment by montaga** [comment]
Hmm, maybe you have set the flag `autoplay: true`? If you set it to `false`, then the move-script should only be evaluated when there is a (mouse) interaction

**Comment by q2apro** [comment]
Now in the fiddle, it runs only on mouse over:

https://jsfiddle.net/kai_noack/y1ck7pjs/

Not sure what caused the effect before. I report back when I find out.
