### ISSUE TITLE
Font-Size of drawtext("...", size->17) should be according to stage grid (e.g. 0.7) and not to HTML pt

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#719]
To my understanding the font size is set with pt.

However, this leads to problems when scaling the app / canvas. See here: https://github.com/CindyJS/website/issues/55#issuecomment-447637254

![image](https://user-images.githubusercontent.com/6764548/50053687-08e1dd00-0142-11e9-9a79-3efdc41fa20d.png)

The font size does not scale if you reduce the canvas size (does not matter if CSS or Javascript).

I strongly suggest to change the font size to match the canvas size / grid size to avoid scaling problems.

Or to be able to setup the font-size as percentage (in reference to the defaultAppearance textsize). Maybe that is already possible?!

**Comment by montaga** [comment]
I agree with that. I also would like to have some nice way to specify the font according to the size of the canvas.

**Comment by q2apro** [comment]
My **current workaround** is to specify the font size **only globally** and do not (cannot) touch it in the cindy script itself later on. Which however requires to not change any font-size later on.

See down the `font_size` declaration and the parameter `textsize: font_size,`.

```

	<script>
		var canvas_size = 500; 
		var font_size = 20;
		
		var screen_width = window.innerWidth || window.clientWidth || window.clientWidth;
		
		if(screen_width < 480)
		{
			canvas_size = screen_width;
			font_size = screen_width/27; // 15; // 450 ~ 15, 300 ~ 12
		}
		
		CindyJS({
			scripts: "cs*",
			//autoplay: true,
			ports: [{
				id: "CSCanvas",
				//background: "#EEE",
				axes: false,
				width: canvas_size,
				height: canvas_size,
				transform: [{
					visibleRect: [-1, 7, 14, -7]
				}],
				grid: 1,
			}],
			
			defaultAppearance: {
				/*clip: "none",
				pointColor: [1,0,0],
				lineColor: [0,0,1],
				pointSize: 5,
				lineSize: 1,
				alpha: 1,
				overhangLine: 1,
				overhangSeg: 1,
				dimDependent: 0.7,
				fontFamily: "sans-serif",
				textsize: 20,
				lineHeight: 1.45*/
				textsize: font_size,  // HERE
			},
			
			geometry: [
				{name:"A", kind:"P", type:"Free", pos:[rect.w, 0]},
				{name:"B", kind:"P", type:"Free", pos:[rect.w, rect.h], color:[0,0,0], pinned:true, size:3},
				{name:"C", kind:"P", type:"Free", pos:[0, rect.h], color:[0,0,0], pinned:true, size:3},
				{name:"D", kind:"P", type:"Free", pos:[0, 0], color:[0,0,0], pinned:true, size:3},
			],
		});
	</script>
```

It would be great to define some variables with the CindyJS object as a gateway!

Then this could be used to pass integers for the font-size.

**But of course, best solution is to define the font-size based on the grid size!**

**Comment by q2apro** [comment]
It would be great to have the font-size based on the "grid size" (unit size) as soon as possible.

Then cindyjs would scale nicely on all mobile devices!!

**Comment by q2apro** [comment]
I am certain that 99 % of users would benefit from this change. Since I discovered cindyJS I was irritated that it does not scale to mobile screens. More than 50 % of my website visitors are coming by mobile phone. This should be taken into account.

> if you display a construction on a large screen (like an interactive whiteboard) you do not want the fonts to grow proportionally.

This is a rare use case, I bet.

Two solutions would be (also for backwards compatibility) to:

A. have an extra parameter, e.g. `scalefont` that you pass additionally.
B. pass a string for the font-size parameter, e.g. `100%`. Then we could identify: if int then have the font size fixed, if percentage then scale with the canvas.

I vote for B :)

**Comment by q2apro** [comment]
> But then again the fonts might become too small to be readable?

This could happen, depending on the entire scene. Screens of tablets/iPads should not bring issues, they are "big enough". Mobile screens ... well, better scaled then having to move around the entire scene view.

> A. have an extra parameter, e.g. scalefont that you pass additionally.

It would be great to see this implemented in Jan 2019. I really would like to use CindyJS for Matheretter and Mathelounge. See if everything works or if I have to stick with EaselJS and (sometimes) JSXGraph.

**Comment by q2apro** [comment]
**News:** 

I have added the first geometry examples with CindyJS to Matheretter. Love it 👍

https://www.mathelounge.de/602596/mathe-leben-einhauchen-statischen-inhalten-mitmachen-lesers

Wiki article: https://www.matheretter.de/w/punkt

**Comment by q2apro** [comment]
Just to show that a scaling of the font is need, here an example:

1. Width and Height: 300px

![screenshot 2019-01-15](https://user-images.githubusercontent.com/6764548/51173165-7e65d800-18bd-11e9-8454-b58d4fc6cd68.png)

2. Width and Height: 500px

![screenshot 2019-01-15 1](https://user-images.githubusercontent.com/6764548/51173174-832a8c00-18bd-11e9-8259-f75e5601f467.png)

3. Width and Height: 800px

![screenshot 2019-01-15 2](https://user-images.githubusercontent.com/6764548/51173180-89206d00-18bd-11e9-8b09-90bd100cb008.png)

Font scaling is needed :)

**Comment by montaga** [comment]
If I was to redesign the logic of CindyJS, I would introduce a additional postfix unit px (similar as °), where `px=1/screenresolution()`.
Then with `size->1` one would have a thickness of one "grid-unit" and with `size->3px` one would have a thickness of 3 CSS pixels. A coordinate with offset could be computed with `(5,7)+(3px, 3px)`.

But for this point, I would say, backward compatibility and compatibility is important. One option would be to specify "grid-unit" sizes with alternative modifiers.

**Comment by kortenkamp** [comment]
If *I* were to redesign, I'd introduce a measure that is given by a function. And in fact, you could already do so by writing
```size(units, pixel) := units + pixel / screenresolution()```
and using `fontsize->size(units, pixel)`.

**Comment by kortenkamp** [comment]
Wouldn't it be nice to have a postfix-notation for functions? Then we could define

`(x)px :=x/screenresolution();`

and @montaga's example would work.

**Comment by kortenkamp** [comment]
So, as a final solution, I just recommend the following: use a multiple of `screenresolution()` for the text size.

**Comment by q2apro** [comment]
> Hm. I still don't see that it is necessary to scale…

See the screenshots how the labels of the y-axes "move away" from the axes because the font-size is not scaling.

I still do not understand how i can already now define the font-size :/ Could you provide some code for this? Thanks!

**Comment by q2apro** [comment]
As en example: Drawing a fraction circle and having 1 / 4 on the stage.

Big screen:

![image](https://user-images.githubusercontent.com/6764548/51372033-86fc1f80-1b04-11e9-901c-f5e9eb744948.png)

Small screen:

![image](https://user-images.githubusercontent.com/6764548/51372053-95e2d200-1b04-11e9-9a7a-488fbd46dd3d.png)

Code: https://jsfiddle.net/kai_noack/e8L0xazp/3/

What's the proper way to define the font-size dynamically?

**Comment by q2apro** [comment]
One way I found now, in the `draw:` section:

```

fontsize = 30;
if(screenresolution()<30, 
	fontsize=15;
	TextZaMinus.size=10;
	TextZaPlus.size=10;
	TextNeMinus.size=10;
	TextNePlus.size=10;
);

drawtext((4.7,4), zahler, align->"center", size->fontsize);
drawtext((4.7,3.5), "―", align->"center", size->fontsize);
drawtext((4.7,2.9), nenner, align->"center", size->fontsize);
```

But isn't it *inconvenient* to make it necessary to program the font-size? ...

**Comment by q2apro** [comment]
That's the information that I needed. Thanks a lot! ... Please add this quite important bit of information to the docs. :)

**Comment by kortenkamp** [comment]
Like, here: https://doc.cinderella.de/tiki-index.php?page=Script+Coordinate+System&highlight=screenresolution ? 

I always recommend to look into the original Cinderella documentation, as CindyJS should be compatible…

**Comment by q2apro** [comment]
> In contrast to hyperbolic and spherical views, Euclidean views have the same screen resolution everywhere. This function gives the number of pixels between the origin and point [0,1]. If several Euclidean views for the same construction are open, the function will return the maximum of all individual screen resolutions.

Yes, I have seen that part but did not understand. It sounds a bit complicated. 

> screenresolution() tells you how many pixels are in one unit.

Here I got it. 💡

**Comment by q2apro** [comment]
> But still, it would be easier to define the font size as scalable by default in the main setup. ;)

Will this (and the overall scaling of the cindyjs canvas) be implemented in the future? It would be very helpful.

I thought we could make a `mobile` scale option optionally, but since more than 50% of visitors come by mobile, it is a must nowadays. So the scaling is IMHO mandatory :)
