### ISSUE TITLE
Is it save to embed user-generated CindyJS on a website?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#726]
I am considering to implement a way for my 20k users at https://www.mathelounge.de/ to use CindyJS as a scripting language. This way they could easily create interactive geometry on-site.

I am using already very simple embed syntax for drawings and plots:

    ~plot~ x^2 ~plot~
    ~draw~ punkt(0,0 "A") ~draw~

More information: https://www.mathelounge.de/508965/ubersicht-eingabemoglichkeiten-einbettungen-mathelounge

Now I could implement something like:

    ~cindyjs~ {code} ~cindyjs~

However, as I know that Javascript can be executed, would it be safe enough?!

**Comment by kortenkamp** [comment]
I thinkyou gave the answer yourself... you can execute arbitrary JS... does not sound safe to me.

**Comment by strobelm** [comment]
I'm certainly no expert on JS security, but since we open source you could create have your own branch that removes the `javascript` command. I'm not sure if there are other possibly dangerous commands, though.

**Comment by q2apro** [comment]
Is there any plan that CindyJS can be written on https://cindyjs.org/ and then shared?

Like desmos, geogebra and others are doing it?

Then I could iframe-embed this link onto mathelounge.

**Comment by kortenkamp** [comment]
No. We consider content to be fully owned by authors, and we do not have resources to set up a content repository. These are just two of the reasons why this won’t happen. If you check the TOS of GeoGebra (don’t know about desmos) you see that you basically have to donate your content to them, which I do not consider fair. 

CindyJS focuses on performance and mathematical correctness, and the code to include your creations on your site is small, so there is no need to iframe IMHO.

**Comment by q2apro** [comment]
Thanks for the feedback. Very much appreciated.

**Comment by q2apro** [comment]
I made it possible to provide CindyJS using JSFiddle, see the Mathelounge news: https://www.mathelounge.de/597128/news-cindyjs-auf-den-lounges-nutzen-interaktive-geometrie
