### ISSUE TITLE
Providing CindyJS on a CDN

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#728]
It would be great to have CindyJS on a CDN, such as https://cdnjs.com/

Thank you for consideration.

**Comment by montaga** [comment]
In theory, you should be able to use
https://cdn.jsdelivr.net/gh/CindyJS/deploy@v0.8/Cindy.js
which mirrors
https://github.com/CindyJS/deploy/tree/v0.8, which is generated through https://github.com/CindyJS/CindyJS/pull/33.

`v0.8` can be replaced by other versions.

**Comment by q2apro** [comment]
Using the CDN with e.g. https://cdn.jsdelivr.net/gh/CindyJS/deploy@v0.8.7/Cindy.css throws:

>  Package size exceeded the configured limit of 50 MB. Try https://github.com/CindyJS/deploy/tree/v0.8.7/Cindy.css instead.
