### ISSUE TITLE
Reading a variable in init, draw and move block?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#736]
This is what I am using:

```
var cdy = CindyJS({
    scripts: {
        init: `resetclock(); animpoint = true;`,
        draw: `if(animpoint==true, // ... do stuff here ... // )`,
        move: `print(animpoint);`,
```

It seems that the variable is not passed between them.

Original problem is that I need to detect when a point got moved and disable an animation on the canvas.

**Comment by montaga** [comment]
actually, this _should_ work. Maybe there is a problem somewhere else? (developer console?) Comments are in CindyScript are C-Style, i.e`/* ... do stuff here ... */ `

**Comment by kortenkamp** [comment]
I just wanted to say „works as expected“ ;-) 

The move event is called when the construction is moved (and recalculated) internally. Thus it will be called before draw. Actually it can and will be called several times between two draw events if tracing of constructions is necessary.

**Comment by q2apro** [comment]
Thanks for the clarification! 👍
