### ISSUE TITLE
How to detect click and move of point?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#737]
I want to run a function only after a click or move of a point A has been done by the user.

I could not find this information in the docs. 

Maybe `mover()` is one way to do it? However, `if(mover() == "A", /* do stuff */)` does not work.

**Comment by strobelm** [comment]
```mover``` is the operator you are looking for. It yields a handle to the GeoObject and its name is just a property. Comparing ```mover().name``` should work.

**Comment by q2apro** [comment]
Thanks a lot, it works:

```
if(
	mover().name == "A", 
	animpoint = false;
);
````

**Comment by strobelm** [comment]
I think there is no switch, currently. You could detach the console completely (see https://cindyjs.org/ref/createCindy.html#csconsole).

**Comment by q2apro** [comment]
> If it is null, error output will be suppressed except for output to the web developer console.

I tried `csconsole: null,` but still the console shows `Not moving anything at the moment`.

**Comment by montaga** [comment]
The console for `csconsole: null` is the web developer console.

Anyway, with the next release of CindyJS (or https://cindyjs.org/dist/snapshot/Cindy.js), `Not moving anything at the moment` will not be shown anymore: https://github.com/CindyJS/CindyJS/commit/eb21b529bc200b7c4295eb1356d4b7d5dcb6b699
