### ISSUE TITLE
How to draw an angle in Cindyjs?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#739]
I would like to draw a wedge that represents an angle:

![image](https://user-images.githubusercontent.com/6764548/51231072-e292a580-196a-11e9-93c9-3fdf4c501baf.png)

In EaselJS I used `shape.graphics.arc(x, y, radius, startAngle, endAngle);`

How to do this with CindyJS? I do not get it to work with `drawarc(‹point1›,‹point2›,‹point3›)`, see: https://jsfiddle.net/kai_noack/uLabvpqh/1/

What I need is to **specify a start and end angle** and it draws the arc with a given radius.

It would be great to have such a function in core, because I use it widely with geometry drawings.

<br>
PS: It would be great to have a library of all cindyjs examples where you can search through the entire source code. This way I would search for "drawarc" and see if there is something I can use. I searched the gallery by looking at the preview images only.

**Comment by q2apro** [comment]
Wow, insane! ... Even though I don't understand the code yet.

How would I throw-in an angle in degree?

Example: 45°

`anglemarkdeg((0,0),(1,0), 45, 0.5);`

**Comment by montaga** [comment]
just use `(cos(45°),sin(45°))`.

**Comment by q2apro** [comment]
However, `(cos(270°),sin(270°))` would not work.

**Comment by montaga** [comment]
with the updated comment it should work

**Comment by montaga** [comment]
use `draw(shape)` to draw the line around the shape end. And build a helper function `polar(alpha):=(cos(alpha),sin(alpha))` that can be plugged in for `A` and `B`

**Comment by q2apro** [comment]
Thanks again. `draw(shape)` works :)

> We need a startAngle and an endAngle for the wedge.

I don't see the solution for this last part.

**Comment by q2apro** [comment]
This is the recent code, slightly adapted: 

			linesize(3);
			drawcircle((0,0), 4.5);
			anglemark(P,A,deg,r,line):=(
			  B = (cos(deg°),sin(deg°));
			  d = det(P,A,B);
			  shape = if(d~=0,
				 halfplane(join(P,A), P+[ [0,-1], [1,0] ]*(A-P)),
				 if(d>0,
				   halfplane(join(P,A),B)~~halfplane(join(P,B),A),
				   screen()--(halfplane(join(P,A),B)~~halfplane(join(P,B),A))
				 )
			  )~~circle(P,r);
			  if(line, draw(shape));
			  fill(shape, alpha->.3)
			);
			
			anglemark((0,0), (1,0), 270, 4.5, true);

`anglemark((0,0), (1,0), 270, 4.5, true);`

should be:

`anglemark((0,0), (1,0), anglestart, angleend, 4.5, true);`

**Comment by q2apro** [comment]
Thanks a thousand, it works!

(Still it bothers me that i don't understand the code yet...)

Here is the function I am going to use:

```
			linesize(3);
			drawcircle((0,0), 4.5);

			polar(alpha):=(cos(alpha),sin(alpha));

			anglemark(P, degstart, degend, r, line) := (
			  A = polar(degstart°);
			  B = polar(degend°);
			  d = det(P,A,B);
			  shape = if(d~=0,
				 halfplane(join(P,A), P+[ [0,-1], [1,0] ]*(A-P)),
				 if(d>0,
				   halfplane(join(P,A),B)~~halfplane(join(P,B),A),
				   screen()--(halfplane(join(P,A),B)~~halfplane(join(P,B),A))
				 )
			  )~~circle(P,r);
			  if(line, draw(shape));
			  fill(shape, alpha->.3)
			);
			// call
			anglemark((0,0), 145, 190, 4.5, true);
```

**Comment by q2apro** [comment]
Note: One issue is if you play around and want a full circle, then `anglemark((0,0), 0, 360, 4.5, true);` will only show half a circle. But well, if i want a full circle, I am using `drawcircle()` obviously 😉

**Comment by q2apro** [comment]
The code in action: https://jsfiddle.net/kai_noack/b4qgpz9L/1/

![image](https://user-images.githubusercontent.com/6764548/51244891-df111580-198e-11e9-8dac-c3685fcb0060.png)

Love it! ❤️ 

I have added fillcolor and fillalpha to the function:

```
			polar(alpha):=(cos(alpha),sin(alpha));

			anglemark(P, degstart, degend, r, line, fillcolor, fillalpha) := (
			  A = polar(degstart°);
			  B = polar(degend°);
			  d = det(P,A,B);
			  shape = if(d~=0,
				 halfplane(join(P,A), P+[ [0,-1], [1,0] ]*(A-P)),
				 if(d>0,
				   halfplane(join(P,A),B)~~halfplane(join(P,B),A),
				   screen()--(halfplane(join(P,A),B)~~halfplane(join(P,B),A))
				 )
			  )~~circle(P,r);
			  if(line, draw(shape));
			  fill(shape, alpha->fillalpha, color->fillcolor)
			);
```

**Comment by q2apro** [comment]
Everything seems to work now. I stumbled only over one **visual bug** when using lines around the wedges. With linesize(10) is is obvious to see:

![image](https://user-images.githubusercontent.com/6764548/51256178-6cfbf900-19ad-11e9-81fd-a10672d93548.png)

without a line around the objects, it looks perfectly:

![image](https://user-images.githubusercontent.com/6764548/51256221-88670400-19ad-11e9-95c7-35fe0fe1bfe1.png)

Any idea how to fix this?

**Comment by q2apro** [comment]
I fixed it by first filling then drawing the lines!

```
anglemark(P, degstart, degend, r, line, fillcolor, fillalpha) := (
	A = polar(degstart°);
	B = polar(degend°);
	d = det(P,A,B);
	shape = if(
			d~=0,
			halfplane(join(P,A), P+[ [0,-1], [1,0] ]*(A-P)),
			if(
				d>0,
				halfplane(join(P,A),B)~~halfplane(join(P,B),A),
				screen()--(halfplane(join(P,A),B)~~halfplane(join(P,B),A))
			)
	)~~circle(P,r);
	fill(shape, alpha->fillalpha, color->fillcolor);
	if(line, draw(shape));
);
```

Last two lines :)

**Comment by q2apro** [comment]
@montaga 

I thought that the P of your `anglemark()` function stands for the position of the circle, however, when changing P to another position, the function does not work anymore.

Example: https://jsfiddle.net/kai_noack/b4qgpz9L/3/

I guess either we need a fix here, or probably easier: How to put all wedges into a "container object" and then move only this container?

**Comment by montaga** [comment]
you should compute
```
A = P+polar(degstart°);
B = P+polar(degend°);
```

**Comment by q2apro** [comment]
Thanks a thousand! ❤️

**Comment by q2apro** [comment]
An addition way to draw angles (wedges) if you have **3 given points**: 

```
unit(v) := ( 
	v.x/sqrt(v.x*v.x+v.y*v.y), v.y/sqrt(v.x*v.x+v.y*v.y);
);

drawwedge(p1, p2, p3, wradius, wcolor) := (
	fillarc(p1+radius*unit(p2-p1), A+radius*unit(p3+p2-2*p1), A+radius*unit(p3-p1), color->wcolor);
	fillpoly( [p1, (p1+radius*unit(p2-p1)), p1+radius*unit(p3-p1)], color->wcolor);
	draw( [p1+radius*unit(p2-p1), p1+radius*unit(p3-p1)], color->wcolor, size->1.5);
);
```

See it lovely in action here: https://www.matheretter.de/wiki/beliebiges-dreieck

Or Fiddle: https://jsfiddle.net/kai_noack/qnth3049/7/

<br>

PS: Credits go to https://www.mathelounge.de/642821
