### ISSUE TITLE
How to access the x-th element in a list in CindyJS?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#745]
Example:

```
allpoints = [X0,X1,X2,X3,X4,X5,X6,X7];
print(allpoints); // works

// now we want to get the first element in the list
print(allpoints[0]); // does not work
print(allpoints_0); // does not work
```

The docs do not explain how to do this: https://cindyjs.org/ref/Elementary_List_Operations.html

**Comment by montaga** [comment]
check out https://cindyjs.org/ref/Lists_and_Linear_Algebra.html (indexing starts with 1)

**Comment by kortenkamp** [comment]
By the way, I can recommend just having a look into the Cinderella.2 manual (available from Springer-Verlag) ;-)

**Comment by q2apro** [comment]
Thanks for the tip! 👍 Just bought the book at https://www.springer.com/gp/book/9783540349242
