### ISSUE TITLE
How to draw an ellipse in CindyJS?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#746]
With EaselJS there is a prepared function: [drawEllipse (x,  y,  w,  h)](https://www.createjs.com/docs/easeljs/classes/Graphics.html#method_drawEllipse)

How to do the same in CindyJS?

Thanks in advance.

---

Edit: I found this example: https://cindyjs.org/examples/EllipseWithPaper.html but there is no function used to draw the circle/ellipse.

**Comment by montaga** [comment]
compare with https://cindyjs.org/examples/63_Conic_from_Script.html. You need to specify the [matrix](https://en.wikipedia.org/wiki/Matrix_representation_of_conic_sections) of the desired ellipse.
