### ISSUE TITLE
Fit Texture to drawn polygon/rectangle or clip the texture

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#748]
Goal: Draw rectangle with apple-pie-texture. Texture has different width and height than the rectangle.

Example: https://jsfiddle.net/kai_noack/gemLrf2v/2/

How to fit the texture onto the rectangle? Or: How to clip the texture?

```
var cdy = CindyJS({
    scripts: {
        init: ``,
        draw: `
cake = [ (0,0), (12,0), (12,6), (0,6) ];
linecolor((0,0,0));
linesize(3);
drawpoly(cake, color->(0,0,0));
fillpoly(cake, color->(0.8,0.6,0.3), alpha->0.5);

drawimage(A, B, "applepie", rendering->"fast");

		`,
    },
	
	images: {"applepie": "https://st.depositphotos.com/1944723/2226/i/950/depositphotos_22261411-stock-photo-apple-pie-texture.jpg"},
	
    geometry: [
        {name:"A", kind:"P", type:"Free", pos:[0, 0]},
        {name:"B", kind:"P", type:"Free", pos:[12, 0]},
    ],

    ports: [{
        id: "cscanvas",
	transform: [{
            visibleRect: [-1, 7, 13, -1]
        }],
        width: 500,
        height: 320,
	grid: 1,
    }],
    csconsole: false,
    autoplay: false
});
```

Found those docs:
https://cindyjs.org/ref/Image_Manipulation_and_Rendering.html#drawimage$5
https://cindyjs.org/docs/cindygltutorial/textures.html

But they do not answer the question.

**Comment by montaga** [comment]
You can use the command `clip(cake);` before calling `drawimage`
(compare https://cindyjs.org/ref/Shapes.html#clip$1 )

**Comment by q2apro** [comment]
Perfect, exactly what I needed.
