### ISSUE TITLE
Correct way of drawing an annulus (ring) with sections in CindyJS?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#749]
Goal:

![image](https://user-images.githubusercontent.com/6764548/51328547-4c4ea480-1a7c-11e9-81ce-a862f8112aa2.png)

I am using the [function anglemark()](https://github.com/CindyJS/CindyJS/issues/739) from @montaga to draw angles (wedges). And it yields:

![image](https://user-images.githubusercontent.com/6764548/51328722-acdde180-1a7c-11e9-98f4-526e77cc8088.png)

Code:

```
var cdya5 = CindyJS({
    scripts: {
        init: `
polar(alpha):=(cos(alpha),sin(alpha));

anglemark(P, degstart, degend, r, line, fillcolor, fillalpha) := (
A = polar(degstart°);
B = polar(degend°);
d = det(P,A,B);
shape = if(
        d~=0,
        halfplane(join(P,A), P+[ [0,-1], [1,0] ]*(A-P)),
        if(
        d>0,
        halfplane(join(P,A),B)~~halfplane(join(P,B),A),
        screen()--(halfplane(join(P,A),B)~~halfplane(join(P,B),A))
        )
)~~circle(P,r);
fill(shape, alpha->fillalpha, color->fillcolor);
if(line, draw(shape));
);
`,
        draw: `
cradius = 5;
linecolor((0,0,0));
linesize(2);
drawcircle((0,0), cradius);

i = 0;
pieces = 7;
pieceangle = 360/pieces;
while(
i<pieces,
fillcol = (1,1,1);
if(i==1, fillcol = (1.0, 0.5, 0.1));
anglemark((0,0), i*pieceangle, (i+1)*pieceangle, cradius, true, fillcol, 1);
i = i+1;
);
`,
    },
    geometry: [
    ],

    ports: [{
        id: "cscanvas-a5",
        transform: [{
            visibleRect: [-5.5, 5.5, 5.5, -5.5]
        }],
        width: 120,
        height: 120,
    }],
    
    csconsole: false,
    autoplay: false
});
```

I can draw an **inner circle** that covers the main circle and the effect looks like an annulus.

```
// covering circle
linesize(3);
drawcircle((0,0), cradius-2, color->(0,0,0));
fillcircle((0,0), cradius-2, color->(1,1,1));
```

Result:

![image](https://user-images.githubusercontent.com/6764548/51328957-24ac0c00-1a7d-11e9-8998-e3a0f7b30c10.png)

But maybe there is a better way?

**Comment by montaga** [comment]
You could try [to subtract](https://cindyjs.org/ref/Shapes.html#combining-shapes) the inner circle from shape, i.e. insert the line `shape = shape -- circle(P,r/2);` before you use the `fill` command.

**Comment by q2apro** [comment]
Thanks for the tip!
