### ISSUE TITLE
Cindyjs.com - This site can’t be reached

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#765]
https://cindyjs.org/dist/latest/CindyJS.css
https://cindyjs.org/dist/latest/Cindy.js

![image](https://user-images.githubusercontent.com/6764548/53471610-f2270300-3a6d-11e9-9ab6-38bf5379cd93.png)

Since I am using those files as "CDN", all my applications do not work now :/

**Comment by kortenkamp** [comment]
This was just a temporary server outage. Sorry for that.
