### ISSUE TITLE
How to draw a diagram (such as bar graph) with CindyJS?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#771]
I have checked the docs, the gallery and the Cinderally 2 ebook, but could not find a best practice how to draw a bar graph (Säulendiagramm/Balkendiagramm).

Let's say we had some data like:

```
1   1.5
2   3
3   5
4   8
```

and this should become a bar graph. 1 .. 4 as x values and the other values for y.

For Ref: https://de.wikipedia.org/wiki/Diagramm#Achsendiagramme

**Comment by q2apro** [comment]
I am one step further, using:

```
	geometry: [
		{name:"A", kind:"P", type:"Free", pinned: true, pos:[1, 2], color:[0,0,0], labeled:false, size:3 },
		{name:"B", kind:"P", type:"Free", pinned: true, pos:[2, 2.5], color:[0,0,0], labeled:false, size:3 },
		{name:"C", kind:"P", type:"Free", pinned: true, pos:[3, 1.5], color:[0,0,0], labeled:false, size:3 },
		{name:"D", kind:"P", type:"Free", pinned: true, pos:[4, 4.5], color:[0,0,0], labeled:false, size:3 },
	],
```

and in the draw block:

```
		draw((A.x,0),(A.x,A.y), color->(cblack), size->15);
		draw((B.x,0),(B.x,B.y), color->(cblack), size->15);
		draw((C.x,0),(C.x,C.y), color->(cblack), size->15);
		draw((D.x,0),(D.x,D.y), color->(cblack), size->15);
```
which gives me:

![image](https://user-images.githubusercontent.com/6764548/53827078-ea41f400-3f82-11e9-894d-c1b57b9d8fa4.png)

The line have curved endings and I could not find a way to make the endings squared, because then it would look like a diagram/bar plot.

**Comment by strobelm** [comment]
You can use lineCap
```
draw([[-1, -1], [1, -1]], lineCap -> "square", size->10);
```

**Comment by q2apro** [comment]
Thanks, the result is:

![image](https://user-images.githubusercontent.com/6764548/53844244-c647d800-3fad-11e9-8561-82b92c24fcb5.png)

I needed to modify the y value for the drawing (offset 0.1), so that the line would not go below the x-axis.

`draw((A.x,0.1),(A.x,A.y), color->(cblack), size->15, lineCap -> "square");`

Result:

![image](https://user-images.githubusercontent.com/6764548/53844344-16bf3580-3fae-11e9-9f40-6222f8bb0f40.png)

**Comment by montaga** [comment]
`lineCap -> "butt"` should do the same.

**Comment by q2apro** [comment]
Yes, `lineCap -> "butt"` is the way to go. Thanks!
