### ISSUE TITLE
Font displaying subscript unicode

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#772]
Since CindyJS `drawtext` does not come with HTML (I know, Latex would be an option for sophistacted things), and I like to label my points with P₁, P₂ etc. I tried to set the text directly. Result:

![image](https://user-images.githubusercontent.com/6764548/53825661-794d0d00-3f7f-11e9-9ad9-10ca98de90ee.png)

As you can see, the positions of the subscript numbers 1 and 2 are higher than expected.

I guess it is a font issue? It even looks like that 1 and 2 are in a different font.

Here are all subscript unicodes I need: `x₀x₁x₂x₃x₄x₅x₆x₇x₈x₉x₊x₋x₍x₎x₌`

**Comment by strobelm** [comment]
Hi! I think the Rendering is fine, see for example the [Wikipedia article](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) on subscripts in unicode:

![screenshot_20190305_190212](https://user-images.githubusercontent.com/14185442/53829769-2bd19f80-3f81-11e9-91b4-7ef769d80a84.png)

Using TeX should a proper solution:

![screenshot_20190305_185756](https://user-images.githubusercontent.com/14185442/53829886-7a7f3980-3f81-11e9-85cd-0cff7c3b7c1a.png)


I will close the issue. Please let us know if you still think this is a CindyJS bug.
