### ISSUE TITLE
Capturing a single mouse down click in CindyJS?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#779]
I could not find anything about it in the docs nor the Cinderella 2 Manual PDF.

Solely:

> Mouse Down: This slot and the following three slots are very useful for programming user interfaces in CindyScript. A script in this slot is executed whenever the mouse button is pressed. With the function mouse() the current mouse coordinates can be read within a script.

But no example of how to capture the mouse click event. And then execute my code.

**By the way, cindyjs.org is down! https://cindyjs.org/

**Comment by strobelm** [comment]
You can use something like this:
```
<script id="csmouseclick" type="text/x-cindyscript">
println("Clicked");
</script>
```

This isn't documented yet.

**Comment by q2apro** [comment]
Seems to work, thanks!

Fiddle: https://jsfiddle.net/kai_noack/Lc78dr3y/6/
