### ISSUE TITLE
Mistake in Latex example in Cindyjs docs - and Latex rendering bug

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#783]
https://cindyjs.org/ref/TeX_Rendering.html

```
drawtext(
  (0,0),
  "Sum formula: $\sum_{i=1}^n i^2 = { 2\cdot n^3+ 4\cdot n^2 +n\over 6 }
);
```

correct would be:

```
drawtext(
  (0,0),
  "Sum formula: $\sum_{i=1}^n i^2 = { 2\cdot n^3+ 4\cdot n^2 +n\over 6 }$"
);
```

but I just see that the formula is cut off:

![image](https://user-images.githubusercontent.com/6764548/55934115-4bbb4980-5c38-11e9-9672-4022a043c0f2.png)

https://jsfiddle.net/kai_noack/wcg57f84/6/

Correct rendering should lead to:
![image](https://user-images.githubusercontent.com/6764548/55934190-802f0580-5c38-11e9-8409-73cfe959f9d5.png)

**Comment by montaga** [comment]
Thank you for this report.

In your example the formula is cut of because visibleRect was too small. If you increase it, then it looks fine: https://jsfiddle.net/tx9cyuo7/
