### ISSUE TITLE
How to rotate text in CindyJS?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#792]
I could not find the method of how to rotate text... does it work with drawtext()?

https://cindyjs.org/ref/Texts_and_Tables.html says nothing about rotation.

**Comment by kortenkamp** [comment]
No, there is currently no way to rotate text. You could draw text to a canvas and rotate that when you draw it.

**Comment by montaga** [comment]
Are we happy with the semantic of https://github.com/CindyJS/CindyJS/pull/729 ? This would be an easy solution for rotating text.

**Comment by kortenkamp** [comment]
Not sure. We have to rethink text anyway IMHO - in conjunction with screen vs logical coordinates. And other viewports. 

On the other hand - this won’t destroy any backwards compatibility, so maybe it’s worth to just try (as an experimental feature that might be removed).

**Comment by montaga** [comment]
Now you should be able to use `drawtext((0,0),"test",angle->45°);` with the current snapshot to rotate text ([example in live-editor](https://cindyjs.org/editor/?&draw=drawtext((0%2C0)%2C%22test%22%2Cangle-%3E45%C2%B0)%3B&gslp=%5B%5D))

**Comment by q2apro** [comment]
Thanks and thanks for pointing out the editor! There is finally a list of all "event stages", such as "mousedown-script".
