### ISSUE TITLE
Printing a Cindyjs Canvas as PDF/on paper possible or not?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#797]
Example with Canvas: https://www.matheretter.de/wiki/punkt

![image](https://user-images.githubusercontent.com/6764548/59143264-d66abb80-89d1-11e9-8d90-560f929b8037.png)

When printing (in Chrome):

![image](https://user-images.githubusercontent.com/6764548/59143268-e4204100-89d1-11e9-910d-ab6df033f15e.png)

Is it by design that Cindyjs cannot be printed? Or is something missing in the example? Thanks :)

**Comment by q2apro** [comment]
This page could be printed in the past: https://www.matheretter.de/ab/bruch/105

Now it shows blank canvases.

**Comment by kortenkamp** [comment]
Strange, but I can print it. Works as expected (Safari on macOS).

**Comment by q2apro** [comment]
Confirmed. I have tried it on another laptop (with Windows 10, Chrome), there it works. Maybe it has to do with the new driver of my graphics card (AMD Radeon HD7700, Software v19.5.2)

**Comment by q2apro** [comment]
It seems that changing the "Print Destination" is updating the print and shows the content (guess the website content is loaded again on destination change).
