### ISSUE TITLE
Best practice for naming variables in CindyJS? 

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#802]
I am used from PHP and Javascript to name most of the variables with underscore, e. g. `line_a` or `angle_a`.

In CindyJS this breaks the program, since underscores are used as operators: https://cindyjs.org/ref/Lists_and_Linear_Algebra.html#$5fu

What is the best practice for dividing a variable name? Dots cannot be used, because then it's an object.

<br>
PS: By the way, I realized that we can use variable names (e.g. for angles) such as `α` or `β`. This is quite cool :)

**Comment by kortenkamp** [comment]
You can use CamelCase or you can even use space characters or line breaks. For example, it is legal to write

```
a strange variable = 15;
err(a strange variable);
```

Actually, all white space is just ignored, so you can also do

```
a strange variable = 15;
err(ast rang eva
riable);
```

**Comment by q2apro** [comment]
Wow, that's special (!)

Thanks for the information.
