### ISSUE TITLE
How to set a snap distance for the snap option?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#806]
The `snap` option is very helpful, however, it seems there is no way to set the snap distance. In other words: From which distance the point is snapped to the grid.

Is this feature planned? Or how to achieve it for now?

The snap seems to be 0.1 by default. I tried it here: https://www.matheretter.de/do/loadprog/?id=265

Thanks in advance!

**Comment by strobelm** [comment]
Hi! There is currently no way to modify the snap distance, as far as i know. But you can easily write your own snap function like this:

```
gridsize = 1;
forall(allpoints(),
dist = 0.2;
rx = round(#.x / gridsize) * gridsize;
ry = round(#.y / gridsize) * gridsize;
        if (|rx - #.x| < dist & |ry - #.y| < dist,
            #.xy = [rx, ry];
        );
);
```

**Comment by q2apro** [comment]
That works pretty nice!

Yes, just thought we could add it as an option, because the custom functions I am using for each single script are adding up :)
