### ISSUE TITLE
Errors in the process of exporting .cdy to CindyJS

### ISSUE THREAD

**Issue by kyeong-choi** [CindyJS/CindyJS#811]
I am a math teacher using CindyJS in math education.
I tried to export some CindyLab files (.cdy) into CindyJS with the menu, Export to CindyJS in Cinderella .2.
However, the exported applets were not working well. 

What did I miss some process during exporting CindyJS with CindyLab files?
Please let me know. 
The files can download with the link, https://drive.google.com/drive/folders/1kiEhdDWFTWrXUPWGBuKVKzQwp2b6SybA?usp=sharing

**Comment by kortenkamp** [comment]
I am closing this for now, as we probably fixed a lot of the problems. If you still experience export problems, please submit a new issue. Thanks!
