### ISSUE TITLE
Dot Operators for Arrays

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#822]
For arrays with 2 or 3 entries it is possible to access their entries via .x, .y and .z. But these only work as  getters, and as **not** setters. I.e., something like
```
p = [4, 5];
print(p.x);
```
works while
```
p = [4, 5];
p.x = 8;
```
doesn't. I'd prefer if these dot operators for arrays work both ways or exist not at all.

**Comment by strobelm** [comment]
Hi, good point. While investigating I realized that this does not work on Cinderella either. Perhaps @kortenkamp or @richter-gebert can comment on the intended behaviour.

**Comment by kortenkamp** [comment]
As these setters are not well defined, we prefer to not have them. Just imagine the following code:
```
v=[4,5,6];
v.x=7;
```
Should `v` be interpreted as homogeneous coordinates (as is the case if you use `.x` as a getter) or as a three dimensional vector? There is no way to decide this, so this semantically unclear operation is not supported intentionally.
