### ISSUE TITLE
Changing the color of a segment base condition

### ISSUE THREAD

**Issue by dguimard** [CindyJS/CindyJS#823]
Dear Team,

will it possible to change the color of segment base on dynamic critera : 
 {name: "seg2", type: "Segment", color: [0.0, 0.0, 1.0], args: ["A", "C"], labeled: false}

more generally , how it is possible to access the instance of seg2 and change it property.

Kind regards
david

**Comment by kortenkamp** [comment]
Hi,

you can achieve these effects using CindyScript. If there is a segment called seg2, you can use for example
```
seg2.color = if( A.x < C.x, red(1), blue(1));
```
to change the color of seg2 based on the condition whether A is left of C.

You can find more info about CindyScript on https://doc.cinderella.de, for example.
