### ISSUE TITLE
Cannot remove elements using removeelement

### ISSUE THREAD

**Issue by kortenkamp** [CindyJS/CindyJS#830]
The function `removeelement$1` does not seem to be implemented, as mentioned in #219 as well.

**Comment by strobelm** [comment]
Hi! The code is there https://github.com/CindyJS/CindyJS/blob/master/src/js/libcs/Operators.js#L5225

Are you using a version where the code is active? I am not sure if it part of the latest release. We definitely should do a new release. @montaga would you see some time to do that?

While I was at it: there is now PR #831 to add some unittests.

**Comment by kortenkamp** [comment]
I am using /latest and it is not available there. Actually it would be good if /latest would be really the latest version on master, and to reduce the "make a release" process to assigning a new version number. Would that be an acceptable process?

**Comment by strobelm** [comment]
`latest` points to the latest release, but there is also `snapshot` which points to master:
https://cindyjs.org/dist/snapshot/

**Comment by kortenkamp** [comment]
Great, good to know. This solves the issue for me, but I still hope for faster releases.

**Comment by strobelm** [comment]
We have pushed a new release. Please let me know if this problem persists.
