### ISSUE TITLE
The & operator checks both variables

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#834]
The following code produces an error:
`arr = [];
if(false & arr_1,
  println("Something");
);`

(The error being "WARNING: Index out of range!" and "Condition for if is not boolean".)

I assume this is due to the & operator actually looking at both sides and not stopping when the left/first part evaluates to false. Is there a design reason for this? Personally, I would prefer code similar to the one shown above to work.

**Comment by kortenkamp** [comment]
This is by design and compatible to the Cinderella implementation.

If you really need lazy evaluation, you can use nested ifs:
```
arr = []; if(false,if (arr_1, println("Something");); );
```
