### ISSUE TITLE
Wrong/missleading error message for JSON objects

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#835]
The code
```
p = [3, 4]; 
obj = {"a": p.x};
```
results in the error message "Error: JSON keys have to be strings." The fix is to change the **value** of the JSON object to 
```
obj = {"a": (p.x)};
```
So, the error is not only wrong -- the key is a string after all -- but also doesn't help find the problem.

**Comment by kortenkamp** [comment]
I totally agree, that the error message is wrong and misleading. However, I do not understand in the first place why the additional parentheses are necessary. Or better: I do understand, but I don't like it.

**Comment by BernhardWerner** [comment]
Yes, okay, that's the more reasonable complaint.

**Comment by strobelm** [comment]
Hi. We have already fixes this in #826. 

Problem was the different precedence of operators, because we are using the `:` operator both for JSON and the colon operator, but with flipped key/value semantics. This makes the code harder to parse.
