### ISSUE TITLE
Checking for keys in JSON objects

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#838]
Is it possible to get a function that checks whether a JSON object has a certain key? I.e. I would like to be able to write something like
this:
```
obj1 = {"x": 1, "y": 2}
obj2 = {"x": 3, "y": 4, "z": 5}

forall([obj1, obj2],
    if(hasKey(#, "z"), #.z = -2);
);
```

If it already exists, then I wasn't able to find it in the Reference Manual on the website.

**Comment by strobelm** [comment]
There are several options:
```
obj = {"x": 3, "y": 4, "z": 5};
objKeys = keys(obj); // [x, y, z]

contains(objKeys, "z"); // true
```

or directly (but does not check the key actually)

```
isundefined(obj_"c"); // true
```

If a special function for that would be desired it would be easy to implement.

**Comment by BernhardWerner** [comment]
Oh, thanks! I think both alternatives are more than enough to cover my needs. and while a special function would still be neat, I don't think any more that it is necessary.

**Comment by strobelm** [comment]
Great, happy to help.
