### ISSUE TITLE
Reverse string

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#853]
Can we get a `reverse` function that takes string as input as well as arrays? E.g., `reverse("abcd")` should result in `"dcba"`.

**Comment by kortenkamp** [comment]
Can you use the following workaround
```
sum(reverse(tokenize("abcd","")))
```

**Comment by BernhardWerner** [comment]
Sure! 
But I thought it might be neat to have this provided by the engine. Especially since many array commands like `length` and `_` for indices work for strings, too.

**Comment by strobelm** [comment]
Closed by #854
