### ISSUE TITLE
Shallow copies of JSONs

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#859]
The following code outputs `5` to the console:
```
objA = {"key": 1};
objB = objA;
objB.key = 5;
println(objA.key);
```
Apparently, `objB` is a shallow copy of `objA`. Is there a design reason for this? I was a bit surprised by this, since nothing else in CindyScript is copied shallowly.

**Comment by kortenkamp** [comment]
Well, if you copy a geometric object the behavior will be the same, so I argue that this is the usual design.
Try this with an existing point A.
```
objA = A;
objB = objA;
objB.color = (1,1,1);
println(objA.color);
```
