### ISSUE TITLE
Issue with displaying a fraction

### ISSUE THREAD

**Issue by Regrib** [CindyJS/CindyJS#864]
There is an issue with displaying a fraction in the showcase continuity: https://cindyjs.org/gallery/main/Continuity/
In case 5 the function f(x)=1/(x-2) is not displeased correctly.

**Comment by kortenkamp** [comment]
This is actually just a missing pair of brackets in the CindyScript, and I already fixed this for the next release of the web page. Thank you for your report.

**Comment by Regrib** [comment]
There also is a typo in the showcase https://cindyjs.org/gallery/main/Continuity/
line 3 has an "s" after "such that" which is misplaced.
