### ISSUE TITLE
Higher order functions in CindyScript

### ISSUE THREAD

**Issue by pemukl** [CindyJS/CindyJS#876]
At the moment, CindyScript does not support higher order functions. This means that you can't build functions expecting an un-evaluated function as parameter. 

One can only define global variables which store the required parameters. Here is an example provided by @kortenkamp and @richter-gebert (thank you!):

// global variables #1 and #2  (one could also use an array "params")

plustwo:= (#1=#1+2;#1);
threetimes:= (#2;#2;#2);

#1 = 7; #2 := plustwo;
print(threetimes;); // (((7+2)+2)+2)=13

This could only be fixed by adapting the language design of CindySkript. An inspiration could be the syntactical solution used by JavaScript:
https://en.wikipedia.org/wiki/Higher-order_function#JavaScript

**Comment by kortenkamp** [comment]
With the new release v0.8.15 we introduce `self()` and `eval()`, as well as allowing code to be stored as user fields or JSON object entries. This makes it possible to have a nicer workaround for your feature request. Here is an example that hopefully explains how to use it.

```
o1 = { "name" : "Object 1" };
o1:"identify" := "My name is " + self():"name";
o1:"greeting" := greeting + self():"name";

println(o1:"identify");
println(eval(o1:"greeting", greeting -> "Ich heiße "));

o1:"name" = "Other Object";

println(o1:"identify");
println(eval(o1:"greeting", greeting -> "Ich heiße "));
```

Please try yourself!

**Comment by kortenkamp** [comment]
BTW: This is also implemented in Classic Cindy, available from https://beta.cinderella.de or via `brew install cinderella` (at least on macOS if you use homebrew).

**Comment by kortenkamp** [comment]
I think we can close this, currently, please re-open a new issue if you cannot use the new feature introduced in v0.8.15.
