### ISSUE TITLE
Inconsistencies with degrees

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#878]
I stumbled over two ways degrees are handled that I'm not happy/comfortable with.

#### First: A minus sign turns them into radians.
This code
```
println(-45°);
println((-1) * 45°);
```
returns
```
-0.7854
-45°
```
I think this is a genuine bug and `println(-45°);` should actually return `-45°`.

#### Second: Degree mod degree returns radians.
The code
```
println(mod(456°, 360°));
```
returns
```
1.6755
```
I think this is more okay, but I would still expect to get degrees out of this calculation at first.

**Comment by kortenkamp** [comment]
For your first remark: It is definitely a bug that -45° is not printed in the same way in both cases. I checked with Cinderella, and there both expressions yield -45°.

For your second issue: I agree it should print 96°. But for Cinderella it doesn't. I will change that in Cinderella, I think, as it makes sense to keep the degree setting in that case.

**Comment by kortenkamp** [comment]
FYI: For Cinderella this is fixed in builds >2044.

**Comment by strobelm** [comment]
Hi,

the fix is quite trivial. While investigating I realized that our handling is rather poor for angles in general. Is there an agreement on how to handle those cases?

Cinderella also seems to move to different behavior at some point.

```
println(round(-45.1°));
println(ceil(-45.1°));
println(conjugate(-45.1°));
```

yields 

```
 -1
0
-0.7871
```

**Comment by BernhardWerner** [comment]
> While investigating I realized that our handling is rather poor for angles in general.

I wanted to look through all arithmetic operations and see how they treat angles. Haven't had the time yet. But there are surely more kinks and problems.



> Is there an agreement on how to handle those cases?

My gut feeling says that any rounding should operate on whole degrees. E.g. `round(-45.1°)` should result in `-46°`, I think. So, if I wanted to code, for example, a discretized dial, I would want to be able to write something like
```
angle = round(angle / 15) * 15;
```
and get the angle to be rounded to the nearest 15°.

For `conjugate` itself, I don't have an opinion. In general, I would say that an output should be in degrees if the input is in degrees and there's no explicit reason to change to radians. (E.g. mixing degrees and radians.)

**Comment by strobelm** [comment]
Put up a MR: https://github.com/CindyJS/CindyJS/pull/879 

@kortenkamp @richter-gebert maybe you want to comment on the behavior, especially for conjugate.

**Comment by kortenkamp** [comment]
If you apply `round` and `ceil` to angles you should be pretty sure what you mean. As the `°` is just an operator that divides by 180 and multiplies by π, the resulting angle is *always* in radians. The only thing that happens is the a flag is set that causes Cinderella to display this number differently. This is the same behaviour as with interpreting 3-vectors as points or lines, depending on how they were created.

If we now changed the rounding behaviour, we would change a mathematical operation based on the "representation hint" for that number. I really wouldn't appreciate that – as the function `round` must not be dependent on the usage of the number. Rounding an angle correctly in 15° steps would be written correctly as

```
angle = round(angle/15°) * 15°
``` 

which works correctly currently (both in Cinderella and CindyJS) and is semantically very clear. 

<img width="366" alt="image" src="https://user-images.githubusercontent.com/1773555/180655735-26e988e3-c05e-42ee-964d-a57f0c0cc392.png">

**Comment by kortenkamp** [comment]
For `conjugate` Cinderella does not set the angle flag for the output as well. But, well, if anybody is conjugating an angle, then he or she should be able to live with that…

**Comment by strobelm** [comment]
So let me recap:

we just fix 
1. the flag for the unary minus 
2. mod 

and leave everything else as is. Correct?

**Comment by kortenkamp** [comment]
correct!

**Comment by strobelm** [comment]
Alrighty, pushed the update. Please have a look: https://github.com/CindyJS/CindyJS/pull/879

**Comment by strobelm** [comment]
Closed via https://github.com/CindyJS/CindyJS/pull/879
