### ISSUE TITLE
KaTeX rendering bug in version 0.8.23

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#912]
When using the currently latest version 0.8.23 of CindyJS, I get the following error when I want to render a maths formula:

![chrome_2XdlmfrjkP](https://github.com/CindyJS/CindyJS/assets/14198196/500c5a31-35fb-4918-b837-13301cd7ef33)

In the simple case of, say, 
```
drawtext([0,0], "$123$");
```
the program seems to work fine otherwise, and the text is still rendered. In a more complicated set-up, the whole site crashes. I haven't identified the right combinations of commands yet. But it seems to happened when I draw a maths formula to a texture via the `canvas` command and then try to manipulate the texture via a CindyGL shader.

**Comment by strobelm** [comment]
Thanks for reporting this. Any chance to post an example file?

**Comment by BernhardWerner** [comment]
For the simple case I mentioned, it's really just

```
<!DOCTYPE html>
<html lang="en">
 <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>template</title>
    <script type="text/javascript" src="https://cindyjs.org/dist/v0.8/Cindy.js"></script>
  </head>

<body style="font-family:Palatino; margin:0; font-size:16pt">

<script id='csdraw' type='text/x-cindyscript'>
  drawtext([0,0], "$123$");
</script>

<canvas id="CSCanvas" align="left" valign="top" width="800" height="600" style="border:1px solid #000000;"></canvas>
<script>
var cindy = CindyJS({
  canvasname:"CSCanvas",
  scripts:"cs*",
  use: ["katex"]
});
</script>
</body>
</html>

```

For the more complex case, I'm still trying to find a minimal example that completely crashes. In particular, I suspect it has more to do with my code than changes in 0.8.23. But I'm still investigating.
