### ISSUE TITLE
KaTeX loading from the get go

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#932]
When including KaTeX directly in the CindyJS function, i.e. like
```
cindy = CindyJS({
    // other stuff
    use: ["katex"]
});
```
it only loads the fonts Math and Main, but not, for example, Size_1. Those are only hot-loaded when necessary, i.e. when TeX strings containing the appropriate glyphs is getting drawn.

Moreover, the loading happens asynchronously and is often only finished after the init script already ran. 

Together, this leads to blinking text at the start and whenever new glyphs come along. Which is annoying in and of itself. It also interferes with the fix to `pixelsize` I'm trying to implement, cf. #764.

Is there a reason for why this should be this way? If a user is actively including a plugin, I would expect it to be fully available before the init script starts running. I guess the main reason is that loading KaTeX takes a lot of time? If that's the case, might it be possible to add an option somewhere to force the full load of KaTeX before init runs?

**Comment by kortenkamp** [comment]
Sorry, we have no real way to change this, as we rely on KaTeX. And in particular an old unsupported branch. You might consider looking how to preload fonts for KaTeX, though.
