### ISSUE TITLE
Programatically setting positions for lines

### ISSUE THREAD

**Issue by gagern** [CindyJS/CindyJS#95]
It would be nice if we could set the position of a line from CindyScript. In particular the completely free `FreeLine` and the semi-free lines `Through`, `HorizontalLine` and `VerticalLine`. We already have write access for the `angle` of a `Through`, but changing `homog` should be made to work as well, I think.

**Comment by gagern** [comment]
Some pointers: [`Accessor.setField`](https://github.com/CindyJS/CindyJS/blob/0fb147c879568a98de0f3dbe8615c98791bdbd01/src/js/libcs/Accessors.js#L167-L180) where we'd have to add the additional cases and [`Through.getParamForInput`](https://github.com/CindyJS/CindyJS/blob/0fb147c879568a98de0f3dbe8615c98791bdbd01/src/js/libgeo/GeoOps.js#L186-L193) for an example of how to distinguish between mouse and script input.

**Comment by kranich** [comment]
This is related to #282, #284, #285, #286, #287.

**Comment by kranich** [comment]
@gagern How would you like to update homogeneous coordinates of `HorizontalLine` and `VerticalLine`? Set first respectively second coordinate entry to zero?
